### ISSUE TITLE
Inconsistent names of files saved on the disc (with and without extensions)

### ISSUE THREAD

**Issue by dufia** [jalik/jalik-ufs#102]
Let me quickly explain what I am doing. I have images stored on the server (UploadFS.store.Local) and I want to access them directly via NGINX. Excluding Node.js from the process, because it stresses the CPU.

I save my files with both `.importFromURL` and `new UploadFS.Uploader`. To my surprise, some files saved on the server have extensions and some don't. Actually, files saved with `.importFromURL` look like this `iawHC3o4QtMLqSH68.png` and with `new UploadFS.Uploader` like this `herRwCzkBMza98yWL`.

I guess I could work around it by storing some additional data on the document but It creates unnecessary confusion. Is there a way to make it consistent? One way or another. Thank you! :)

**Comment by jalik** [comment]
Please see the answer on the related package.. 
https://github.com/jalik/jalik-ufs-local/issues/3
