### ISSUE TITLE
Ufs behind a reverse proxy

### ISSUE THREAD

**Issue by Huljo** [jalik/jalik-ufs#104]
I'm trying to use ufs in a subfolder but the webapp handler is not catching my requests (`ROOT_URL=http://www.domain.com/chat/`, meteor is running at localhost:3000, behind nginx).

````javascript
console.log(__meteor_runtime_config__.ROOT_URL_PATH_PREFIX) // "/sub"
console.log(UploadFS.config.storesPath) // "sub/ufs"
````

A POST request is sent to http://www.domain.com/sub/ufs/uploads/BnBYGCKsB9LBYqXeY?token=890B6b7B88&progress=1 by the client application but in the webapp handler ( [here](https://github.com/jalik/jalik-ufs/blob/3e9fd1b82eebd961f10b3fccd40912aeafe1cf1a/ufs-server.js#L49) ) `req.url` is set as "/ufs/uploads/BnBYGCKsB9LBYqXeY?token=890B6b7B88&progress=1" so `req.url.indexOf(UploadFS.config.storesPath)` is returning -1 and skip the request treatment.

**Comment by jalik** [comment]
Hi @Huljo, I haven't verified this yet, but since your `ROOT_URL` is a subfolder, I think it's normal from Meteor's point of view that any request does not contain the `sub` folder, so your `UploadFS.config.storesPath` should point to `ufs` and not `sub/ufs`.

It's what I think, because if you call `Meteor.absoluteUrl()` you'll get `http://www.domain.com/sub/`, then appending the `storesPath` would repeat the sub folder like `http://www.domain.com/sub/sub/ufs`.

I'll check that and confirm it to you.
Sorry for the late response.

**Comment by Huljo** [comment]
Hi @jalik, thank you for your reply. no worries about the delay.
I set `UploadFS.config.storesPath` to  `sub/ufs` because this is the better way I found to define a good URL for the POST request from client.
If I set `UploadFS.config.storesPath` to  `ufs` the client is calling `http://www.domain.com/ufs/uploads/...` and nginx is returing 404 because my app is in a subfolder.

**Comment by Huljo** [comment]
Hi @jalik, did you find time to check ?

**Comment by jalik** [comment]
@Huljo Sorry, I am working on some rework of the current code to use ES6 syntax (import/export and other handy syntaxes). I'll give a check this week !

**Comment by jalik** [comment]
@Huljo I fixed the bug in the `0.7.2` release, please update you packages.
It was not about reverse proxy but more a question of relative/absolute path defined by `ROOT_URL`.
Using a subfolder was causing this issue.

**Comment by Huljo** [comment]
Thank you @jalik! Ill create a PR on Rocket.chat repository to update the package version.

**Comment by jalik** [comment]
@Huljo so did it fixed your problem ? it did for me following your explanations.

**Comment by Huljo** [comment]
I'll be back soon with the results of my tests before my PR :)

**Comment by jalik** [comment]
@Huljo Thanks, let me know if it's ok or not ;)

**Comment by mattlin** [comment]
@Huljo @jalik  Thanks a lot . Hope it will be fixed on Rocket.chat 0.52  :P

**Comment by Huljo** [comment]
Hi @jalik, bad new, the client is still calling the URL "domain.com/ufs/uploads/..." in my case.

**Comment by Huljo** [comment]
Sorry for lack of detail, it was a quick test.
The only sure thing is that **ufs** is up to date (0.7.2) and `ROOT_URL` is well defined to `http://www.domain.com/chat`.
I'll make further testing the next hours.

**Comment by mattlin** [comment]
Hi @Huljo ,  how is it going :stuck_out_tongue_closed_eyes:

**Comment by Huljo** [comment]
Sorry for the delay.
When I set `UploadFS.config.storesPath` to `sub/ufs` the URL called the client is now good (http://www.domain.com/sub/ufs/uploads/73ChKaf6zCLsm4AAw?token=9A3B5B1958&progress=1) 
But the server is throwing an error : 
`Exception while invoking method 'ufsComplete' Error: ENOENT: no such file or directory, open '/tmp/ufs/73ChKaf6zCLsm4AAw'`

**Comment by mattlin** [comment]
hi @Huljo, the client is now good, and how about the issue ["Can't upload files when running in a subdir #4832"](https://github.com/RocketChat/Rocket.Chat/issues/4832) on Rocket.chat ? I was struggling for it for a long time

**Comment by Huljo** [comment]
@mattlin can you confirm that upload is working for you by only adding UFS 0.7.2 ? 
It still not working in my case.

**Comment by Huljo** [comment]
@jalik my folder `/tmp/ufs` is `chown appuser:appuser` and `chmod 700`
Any idea about why the temporary file is missing ?

**Comment by mattlin** [comment]
@Huljo I do not know how to add UFS 0.7.2 for Rocket.Chat. I will test the issue for Rocket.Chat new version.

**Comment by Huljo** [comment]
Sorry for the delay @mattlin,
just change the version here : 
https://github.com/RocketChat/Rocket.Chat/blob/1b7f93efbc1ba4c0cef799370b1074fc853a36df/.meteor/versions#L39

**Comment by HighwayStar** [comment]
I've tried Rocket.Chat develop branch https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/versions#L53 wich said  jalik:ufs@0.7.4_1 and i still doesnt work - generates wrong POST url
