### ISSUE TITLE
The default permission is not "deny all"

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#105]
[the code](https://github.com/jalik/jalik-ufs/blob/3e9fd1b82eebd961f10b3fccd40912aeafe1cf1a/ufs-store.js#L90) says that the default permission is `deny all` but [the store class](https://github.com/jalik/jalik-ufs/blob/4333d8093d6b77d686f61dce09c41039b0501d56/ufs-store-permissions.js#L31) by default uses `allow all`.

**Comment by jalik** [comment]
Thank you @rodrigok, I forgot to change that comment when I modified the default permissions.
I first used a `deny all` policy to force developers to set permissions, but later I changed my mind and switched to `allow all` to allow a quick start with the lib.

**Comment by rodrigok** [comment]
@jalik Thanks
