### ISSUE TITLE
A better way to filter uploaded files

### ISSUE THREAD

**Issue by macman31** [jalik/jalik-ufs#109]
Hey @jalik,

In my use case, I need to only allow users to upload images, and I need to transform those images using `gm` before inserting them in the database.
the `filter` option is designed to do that, by checking for `contentTypes` and by executing a custom `onCheck` function before allowing or rejecting the upload.

## The issue

But the issue I have is that `contentTypes`, and also all the `file` information passed to `onCheck` are derivated from information set by the client (like the extension of the file)! 

That is an issue, because what if an user decides to upload a binary file (not an image) with an image file extension (example: `dotexefile.png`)?
The `filter` will allow the upload to proceed, because both `contentTypes` and `onCheck` can only have access to the "fact" that the image is an `image/png` determined from its extension.

Then `transformWrite` will be executed, and `gm` will send an error because the file content is not an image, despite the fact that it has a `.png` extension!

The write stream will be closed, because `gm` exited, and the rest of the upload process will occur. (set file information, execute `onFinishUpload`, etc).
The issue is that because `gm` exited, no image will actually be stored in the database! That will result in an "image" of size 0 when we try to access it!

That is in my opinion an issue.

## Some work-arounds

To solve this issue, for my use case, I have two choices with the current code base:

1. If the image could not be converted, I can have `gm` generate an "Invalid Image" image and insert it in place of the uploaded file in the DB.
Example:
```
          gm(160, 160, "black")
          .fill("white")
          .gravity("Center")
          .density(160, 160)
          .drawText(0, 0, 'Invalid\nImage')
          .stream("png")
          .pipe(to);
```
But that is not an acceptable way to deal with the issue. For example, if an existing "valid" image already is in the DB and we try to update it with an "invalid/corrupted" image file, the valid file will be overwritten with the "Invalid Image" image.
Also the upload will succeed from the point of view of the client.

2. A better way to handle the issue with the current code is to abort the upload from inside `transformWrite`.
Currently, when `gm` detects that the uploaded file is not an image, I send an `error` event to the `to` stream:
```
if (err) {
          to.emit('error', new Error('The file is not an image'));
}
```
That triggers the cleanup process, and effectively aborts the upload from the user.
That also triggers a lot of errors server-side, as the server warns about this error, and tries to deal multiple times with the cleanup process.
But in my case, the error is expected! I don't want server logs to be filled with errors that I have intentionally caused because I had no other choice.
So this is a better solution than the first, but it is still not optimal.

Note: if you automatically retry the upload [at this point](https://github.com/jalik/jalik-ufs/blob/3e9fd1b82eebd961f10b3fccd40912aeafe1cf1a/ufs-uploader.js#L138), that will break this way to handle the issue.

## A better way to deal with this issue?

Ok, so to sum up, `filter` is not really trustworthy with the current implementation because it relies on client information only, and both work-arounds I can use are not optimal.

We could imagine having a way to gracefully abort the upload from inside `transformWrite`. But I don't think it is the best way to handle the problem: `transformWrite` should only be executed when the write is certain to happen.

In my opinion, a better and more generic way to deal with the issue is to allow the user to optionally specify a function that would be executed right after downloading the temp file, along with modifying a bit how the creation/update of the file information in the file collection is handled.

Let's call this new function "`validateUploadProperties`" for now. This function would take as arguments a `ReadStream` to the temporary file, and the `file` object sent by the client.

The function would then be able to access the temporary file to check its real MIME type based on its content, or to validate other aspects of the content of the file.
It would then be able to modify the `type` of the file in the `file` object, and maybe specify other fields/values in `file` depending on the content of the uploaded file, and it would return the modified `file` object.

If the function `validateUploadProperties` is not defined, it would default to just returning the `file` object passed as an argument without modifying it.

The `filter.check()` would then be executed on this new `file` object returned from `validateUploadProperties`.

The `filter.check()` would also be executed before the call to `validateUploadProperties`

If either call to `filter.check()` fails, then the upload would be cancelled.

Also, the `file` object stored in the collection should be updated after the call to `validateUploadProperties`, so the `type`, `size` and other information about the file could be updated if they are wrong or added in this new function.
Note: The `file` object in the collection could also be updated on-demand in `validateUploadProperties`, but then we would have to make sure to fetch the updated version to use in the rest of the code.

Both checks are needed because in most cases, the user and its uploaded files will behave correctly, and the detected file type based on the extension will match the real file type.
So if we can directly reject the upload based on information sent by the client, we should do so.
`validateUploadProperties` in addition to the second check will then handle the minority of cases where the uploaded file extension does not match the content of the file.

If implemented correctly, the addition of this new function would not break the existing behavior of the app, because it would default to just passing along the `file` object sent by the client, so both checks would still be done on the content of the client.

If we want to go a step further, I'd say that the `filter.check()` before `validateUploadProperties` should be done client-side instead of server-side, but that would break the current behavior if a Store is defined server-side only.

Sorry for the wall of text!
What do you think?

**Comment by macman31** [comment]
Example of a kind of vulnerability that could be gracefully handled by using this new function "`validateUploadProperties`": https://imagetragick.com/
That's an example with imagemagick, but we can also imagine people dealing with video encoding, or any other transform process that needs to rely on the exact type/properties of the file it handles, and that should reject the client if the file is not the one expected based on its real type/properties.

**Comment by jalik** [comment]
Hi @macman31, please checkout the `es6` (https://github.com/jalik/jalik-ufs/tree/es6) branch I am currently working on, you will find a new `Store.validateFile(file)` method.
It's still a work in progress.

Inside this method, you can call `UploadFS.getTempFilePath(fileId);` to get the path of the temp file, not the stream. I cannot pass the same stream that is used to write the file to the store, so for now you'll have to do like that (please). After what you do whatever you want in this method and throw an error if something is wrong, that will cancel the upload et delete the temp file + the file in the collection.

I am still thinking about the possibility to modify the file attributes before writing to the store.. I am not convinced since, if you allow only images in the filter, then it's useless to set image type to `exe` if it's an executable and not an image (as you said in your example).

Still using your example, I found that I cannot catch the `gm` error throwed when you upload an exe that has been renamed with `.jpeg` extension, that just crashed the app, do you have a solution for that ?

Thanks for the wall of text ;)

**Comment by macman31** [comment]
Hey @jalik,

`Store.validateFile` looks ok!
I had a different approach, but yours works too.

The reason I wanted a way to modify the file attributes was because I relied on the filter to validate a file. This way, in my approach, each component would have done its specific job for all the cases: `validateUploadProperties` would have validated upload properties and have them match the real file if needed, the filter would have filtered on the `file` sent by the client and after that on the `file` object modified by `validateUploadProperties`, `transformWrite` would have transformed the uploaded file, etc.
In your solution, modifying the file attribute is not really needed indeed. But you also have to duplicate the filter logic: once in `Store.validateFile` for the validation of the image server-side, once in filter for the data sent by the client.

Regarding the error reported by `gm`, well there is a catch:
https://github.com/aheckmann/gm/blob/master/lib/command.js#L284-L310

Since the operation we do is a conversion, it doesn't need to be buffered, and in this case the `err` is always set to `null` (line 309).

To overcome this issue, I looked at how RocketChat handled the problem with your library, and they handle it quite beautifully imo!
I use this code heavily inspired from their source code:

```
  // Make sure that pictures are indeed images
  transformWrite: function (from, to, fileId, file) {
    let stream = null;
    // identify will return an error if the content of the file is not an image.
    // If it is an image, then details on the image file will be in data.
    const identify = function(err, data) {
      if (err) {
        // Causes an exception and triggers the cleanup process by sending
        // an error event to the 'to' stream
        to.emit('error', new Error('The file is not an image'));
      } else {
        // Save the uploaded picture, after cleaning it.
        gm(stream)
        .autoOrient()
        .noProfile()
        .stream()
        .pipe(to);
      }
    };
    stream = gm(from).identify(identify).stream();
  },
```

Merci pour le support exemplaire que tu offres pour cette librairie ;)

**Comment by jalik** [comment]
@macman31 I don't really see duplication checks in the current workflow :
1 - Client sends file info
2 - Server checks file info using filter, since it cannot do anything more without the real complete file (binary data)
3 - Client's upload is accepted/rejected by the filter
4 - Client uploads file chunks
5 - When upload is complete, the client tells the server it's done
6 - Server validates temporary uploaded file using file info and custom checks (with GM in your case)
7 - If file is valid, it is then written to the store, if not, it's deleted and client is notified of the error.

I've added the `onValidate(file)` store option in which you can validate the file with gm, please use it instead of `validate(file)` which is called by UFS, just in case UFS would need to do some generic validations in the future, do not overwrite it ;)

About the gm error handling, if I understand it cannot be catched from upper levels (inside UFS). I wanted to add a layer of "security" to avoid server crashes in this specific case.

I've merged those changes in the master branch and published the `0.7.2` version containing other improvements. It's time to update ;)

Thanks for your valuable feedbacks and help in improving UploadFS. :)

**Comment by macman31** [comment]
Hey @jalik,

Here is my implementation of `onValidate`. Feel free to modify it/use it as the example for onValidate on the README, as the current given example still use transformWrite to check if the file is an image or not.

Note: it needs an `meteor npm install --save fibers`

```js
import Future from 'fibers/future';

[...]
  // Make sure that gallery pictures are indeed images
  onValidate: function (file) {
    // Here 'file' contains file metadata sent by the client, we need to get
    // the disk path to the uploaded temp file to give it to gm.
    const tempFilePath = UploadFS.getTempFilePath(file._id);

    // Since the 'identify' function below is executed in a callback,
    // we cannot directly throw an exception from it, because the exception would
    // be catched by the server and not by ufs. We need to throw the exception
    // from this onValidate function, so that ufs can catch the exception and
    // trigger the cleanup process/report the error to the client.
    // We do this by defining a future and waiting for it in onValidate, and having
    // the future throw the exception instead of throwing it directly from
    // the 'identify' function.
    let future = new Future();

    // identify will return an error if the content of the file is not an image.
    // If it is an image, then details on the image file will be in data.
    const identify = function (err, data) {
      if (err) {
        // Throw an exception to inform the client and trigger the cleanup process
        future.throw(new Meteor.Error('not-an-image', 'The file is not an image'));
      } else {
        // We need to tell our future to return, or else it would stay stuck.
        future.return();
      }
    };
    gm(tempFilePath).identify(identify);

    // Wait for 'identify' to complete, and either return or throw the exception
    return future.wait();
  },

  // Standardize uploaded pictures
  transformWrite: function (from, to, fileId, file) {
    // Save the uploaded picture, after cleaning it.
    gm(from)
    .autoOrient()
    .noProfile()
    .stream()
    .pipe(to);
  },
[...]
```

Thanks again!

**Comment by jalik** [comment]
@macman31 Thank you for this snippet. I'll put it in the doc.
