### ISSUE TITLE
UploadFS.addETagAttributeToFiles() permission error

### ISSUE THREAD

**Issue by macman31** [jalik/jalik-ufs#112]
Hey @jalik,

While trying to upgrade UploadFS to 0.7.2, I encountered an issue:
The changelog asks to call `UploadFS.addETagAttributeToFiles({etag: null});` once.

I copied this line in my function `Meteor.startup()`, but when the server restarts it causes a `Error: Forbidden [forbidden]`.
It's probably due to the fact that my collection permissions require the owner of the file to be the one doing the update to the collection for that file.

Maybe it would be best to avoid checking for permissions to complete this kind of "global version update"?
You can probably use the [direct version](https://github.com/matb33/meteor-collection-hooks#direct-access-circumventing-hooks) of the update call to avoid checking for them.

**Comment by jalik** [comment]
You're right ! Thanks :)

**Comment by macman31** [comment]
Fixed by @jalik in 3ba9514 (0.7.3)!
Thanks!
