### ISSUE TITLE
Urgent issue! onFinishUpload broken, onRead always returning true, etc.!

### ISSUE THREAD

**Issue by macman31** [jalik/jalik-ufs#113]
Hey @jalik,

Urgent issue:
I noticed that after updating to 0.7.3, the specified function `onFinishUpload` of my stores wasn't executing anymore.
I spent the last few hours trying to track down the issue.

After recreating locally the dev environment for `jalik-ufs`, I was finally able to run a debugger, and here is what I found:
- The store is created
- The function `onFinishUpload` is extracted from the options [here](https://github.com/jalik/jalik-ufs/blob/master/ufs-store.js#L108)
- Then the code continue, and all the other variables are initialized
- Eventually, the code reaches [this line](https://github.com/jalik/jalik-ufs/blob/master/ufs-store.js#L406), we are still in the store creation process, and we are in the server, so the code goes inside the `if`
- Then the code reaches [this line](https://github.com/jalik/jalik-ufs/blob/master/ufs-store.js#L497)! Major issue here! The empty function declaration overrides the custom function specified in the options!!!

This issue is not only with `onFinishUpload`, we can see that `onRead`, `onReadError`, `onWriteError`, etc. are all affected!
`onRead` will always return `true` for example! That's a security issue!!!!

This library probably needs tests!

**Comment by TheAOS** [comment]
I had to make a quick fix to get further along with something I'm working on

In case anyone else needs it, here's the commit: https://github.com/TheAOS/jalik-ufs/commit/563e6499417f0b26a47a612127cf3744d8298855

**Comment by jalik** [comment]
@macman31, @macman31 sorry for the delay, I am very busy these days.
For now it should be fixed, I've tested all event methods.
About unit tests I agree but I don't have time for that, a PR from the community would be great.
Thanks for reporting.
