### ISSUE TITLE
Question: Is it possible to get file from gridFS storage via XMLHttpRequest

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#114]
Hi, 

Is it possible to get a file from the gridFS storage via `XMLHttpRequest`? I try the following code:
```javascript
const file = Files.findOne({ _id: fileID });
file.url = file.url + '?token=' + file.token;

let blobUrl; 

const xhr = new XMLHttpRequest();
xhr.onreadystatechange = function () {
    if (this.readyState === 4 && this.status === 200) {
        const url = window.URL || window.webkitURL;
        blobUrl = url.createObjectURL(this.response);
    }
};
xhr.open('GET', 'file.url');
xhr.responseType = 'blob';
xhr.send();
```
but the app always returns a blob with size = 10892 and type = text/html, although I try to get files with various types (audio, images) and sizes.

Thanks in advance.

**Comment by jalik** [comment]
Hi @seabrus I've tested your method and it works well for me, just be sure to unquote `file.url` in `xhr.open('GET', 'file.url');`.

Here is a modified version :
```js
window.dl = function (url) {
    let preview = document.getElementById('preview');

    const xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function () {
        if (this.readyState === 4 && this.status === 200) {
            const blob = this.response;
            console.log('blob', blob);

            // Create Blob URL
            const url = window.URL || window.webkitURL;
            const blobUrl = url.createObjectURL(this.response);
            console.log('blobUrl', blobUrl);
            preview.src = blobUrl;

            // Convert Blob to base64
            const reader = new FileReader();
            reader.onloadend = function () {
                const b64 = reader.result;
                console.log('base64', b64);
                preview.src = b64;
            };
            reader.readAsDataURL(blob);
        }
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob';
    xhr.send();
};
```

UploadFS is built in separate blocks (server, uploader, store etc). This allows to replace almost any part with your own, like a custom file uploader or a custom file server. Your question is pointing specifically to a GridFSStore but all stores implements the same interface (read, write etc) so whatever the store is, the behavior when writing/reading a file should be the same (just FYI).

Can you confirm it's working on your side ?

**Comment by seabrus** [comment]
Hi @jalik 

>  just be sure to unquote file.url in xhr.open('GET', 'file.url');

damn! Of course! Sorry for taking your time. Let me try to compensate this by sharing the reason why I use that code.

The reason is the [iOS 10 - HTTPS problem](https://poodll.com/ios-10-and-html5-video-and-html5-audio-on-https-sites/):
>There seems to be a bug in iOS 10 that kills HTML5 video and audio playback. The media just fails to load and playback. I noticed it quite soon after iOS 10 was released and at first thought that it was something to do with the SSL certificate that I was using. But a number of sites with SSL certificates from other sources have reported the same.

So, I analysed possible solutions and came to conclusion that using of `XMLHttpRequest` is the most fast and simple one because it get blobs via HTTP. 
Other candidates were:
- Meteor `HTTP` package -- but it does not support `xhr.responseType = 'blob';`, and auxiliary packages that overcome this shortcoming are not supported now by their authors;
- `Meteor.Method` with [`readStream`](https://github.com/jalik/jalik-ufs#reading-a-file-from-a-store-server) -- but it looks as a little complicated way. Moreover, the data, as I can understand, will be passed via DDP instead of HTTP what for somewhat large files may be not the best solution. 

Hope this information helps someone else :) 
And thank you for your support. Have a nice day!

**Comment by jalik** [comment]
Thank you for the explanation, it will be useful for those having the same issue.
About the current question, is it resolved ? can I close the issue ?
Have a nice day.
