### ISSUE TITLE
Attach meta-data to a file? Is this possible?

### ISSUE THREAD

**Issue by thebarty** [jalik/jalik-ufs#116]
Hi guys,

first of all: thanks for this great package. So far it has been awesome to hook up to my project. 👍 

Now I need to add some meta-data to an image. In my useCase an admin can add avatar-images to users, so I need a place to store WHICH user the admin is uploading the image for. I'd love to do something like `$set: { meta: { imageType: 'AVATAR', userId: 'someUserId', .... } }`. 

Is this possible to do? What is the best place to do this?

**Comment by thebarty** [comment]
I think I found the answer: https://github.com/jalik/jalik-ufs/issues/69. Closed!

**Comment by jalik** [comment]
@thebarty I am glad you found it. Maybe it is not obvious in the doc.

**Comment by thebarty** [comment]
Yeah - adding a hint to the docs would make it easier for future users 👍
