### ISSUE TITLE
UFS Filter for client side

### ISSUE THREAD

**Issue by talha-asad** [jalik/jalik-ufs#119]
There are use cases where you want to store images and videos both in one collection. However want to restrict to one type from the client side because you have separate interfaces for both. On the server you allow both images and videos because its the same collection. Having the filter functionality available at the client side would make this possible. Ofc, it won't be much more than extension checking but I guess the server has the same as of now.

**Comment by jalik** [comment]
@talha-asad You can use the same collection in two different stores.
Create a store for your images with an image filter, then create a store for videos with a video filter, a store is how you save your files physically, while the collection only contains meta information.

**Comment by talha-asad** [comment]
That sounds like a pretty neat idea, thanks!

**Comment by jalik** [comment]
@talha-asad let me know if that works like you want.

**Comment by talha-asad** [comment]
@jalik Seems to work as expected. Thanks.

This is a common use case and a great feature, should be mentioned in the Readme.
