### ISSUE TITLE
UploadFS.store.local is not a function

### ISSUE THREAD

**Issue by pacozaa** [jalik/jalik-ufs#121]
Here is my code on server side
``` javascript
import {UploadFS} from 'meteor/jalik:ufs';

const Photos = new Mongo.Collection('photos');

const PhotoStore = new UploadFS.store.Local({
    collection: Photos,
    name: 'photos',
    path: '/uploads/photos'
});
```
Here is my error
![capture](https://cloud.githubusercontent.com/assets/3154089/25736440/0f38a3a4-319c-11e7-8366-e8ec8e37ca07.JPG)

Any idea how to solve this?

**Comment by mdmad7** [comment]
Install localstore package by running 
meteor add jalik:ufs-local
Import it like below:
Import {LocalStore} from 'meteor/jalik:ufs-local';

Change:
const PhotoStore = new UploadFS.store.Local({
To:
const PhotoStore = new LocalStore({

**Comment by jalik** [comment]
@mdmad7 Thanks :)
@pacozaa Sorry, I forgot to reply to this issue...
