### ISSUE TITLE
How to delete uploaded files?

### ISSUE THREAD

**Issue by pizzetto** [jalik/jalik-ufs#128]
I see no documentation on deleting existing file. I am using GridFS, I think is not enough to delete the document in mongo collection.

Thanks

**Comment by jalik** [comment]
@pizzetto when you delete a file in the collection, the "physical" file is also deleted, so you "normally" not have to manage this. But if you need to delete manually a file from a store :
```js
import {GridFSStore} from "meteor/jalik:ufs-gridfs";

const FileStore = new GridFSStore({});
FileStore.delete("theFileID");
```

**Comment by jalik** [comment]
@pizzetto have you found what you needed ?

**Comment by pizzetto** [comment]
I deleted the document as you suggested. I think is enough since i'm using
the db store isn't It?

Il mer 21 giu 2017, 21:22 Karl STEIN <notifications@github.com> ha scritto:

**Comment by jalik** [comment]
@pizzetto Yes it's enough, I just wanted to know if your problem was solved, seems to be :)
Thank you.

**Comment by pizzetto** [comment]
Thank you very much Karl!

Il mer 21 giu 2017, 21:52 Karl STEIN <notifications@github.com> ha scritto:
