### ISSUE TITLE
Uploading aborted in production server

### ISSUE THREAD

**Issue by kasiula03** [jalik/jalik-ufs#134]
Hi.
I can't handle one problem. When I'm uploading images on localhost everythings works fine, but when I build meteor app and start it on remote ubuntu server, then every image is aborted. Any collections of simple types works good.

What do you think?

**Comment by jalik** [comment]
Hi, if you're using imagemagick or graphicsmagick, make sure you have installed them on the server using the `apt` command.
Also make sure that the application has permissions to read and write to the store destination (the folder should be created at startup, if not, there is a problem with permissions.
Finally check the app's logs, you should have something helpful inside.

**Comment by kasiula03** [comment]
Thanku you for answer jalik. I'm using graphicsmagick and I installed them earlier. Strange things have happened because today everything works fine. Maybe something has stuck in cache (is it possible?).
I will try find what's actually has happened because I'm confused right now.

**Comment by jalik** [comment]
@kasiula03 Fine ! problems often happen with environment (settings, libs, etc). Happy coding.
