### ISSUE TITLE
Clever-cloud - no nginx - CORS Issue 

### ISSUE THREAD

**Issue by Gorbus** [jalik/jalik-ufs#135]
The package works like a charm locally with the base upload + gridFs on the meteor integrated mongoDb but when I upload it on clever-cloud (similar to Heroku) with their mongodb addon then a CORS error : 

> POST http://app_fac508e9-b119-42bc-922b-8d09d4dedce1.cleverapps.io/ufs/images/EfMnLHZiFgmC4nPv3?token=08aB4b7B09&progress=0.030616516175327395 404 (Not Found)
> 
>  XMLHttpRequest cannot load http://app_fac508e9-b119-42bc-922b-8d09d4dedce1.cleverapps.io/ufs/images/EfMnLHZiFgmC4nPv3?token=08aB4b7B09&progress=0.030616516175327395. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://app-fac508e9-b119-42bc-922b-8d09d4dedce1.cleverapps.io' is therefore not allowed access. The response had HTTP status code 404.

Any idea how I could solve this ?

**Comment by Gorbus** [comment]
ok problem came from different ID in the environment variable. One url had a "_" while the other one had a "_"....

**Comment by jalik** [comment]
Hi @Gorbus, I am glad you solved your problem, and thank you for using this package :)
