### ISSUE TITLE
converting from CollectionFS

### ISSUE THREAD

**Issue by hluz** [jalik/jalik-ufs#14]
Simple and great package. Congratulations. Currently using CFS/GridFS and intending to move to a smaller and less complicated package for what I need. Issue is, ufs + hfs-gridfs have somehow different structures for the created mongo collections. Wondering what is the best way to convert the existing data in cfs_gridfs.x.files and cfs_gridfs.x.chunks? Would be great if the data structures were compatible and we could use the same collection names, but if too difficult, any possibility of at least a script to move the data across?

**Comment by jalik** [comment]
@rodrigok is the official author and maintainer of the UFS-GRIDFS package, he should be able to answer your question easily, other way this issue is related to the mentioned package so you should publish it directly in the package : https://github.com/jalik/jalik-ufs-gridfs/issues

**Comment by hluz** [comment]
@jalik, my fault for not noticing there was a different maintainer for the two packages. However there are 3 collections in play ( the 2 gridfs ones + the file collection that your package creates for the file info, metadata, etc.). The structure of the third collection could be made compatible with the equivalent one from CFS with a bit of work to make it easier for CFS users to move to your package... :-)

That's for your time.

**Comment by jalik** [comment]
@hluz I created UploadFS because I didn't like the structure of CollectionFS file documents (even if they did a good job). I'll see how I can make it easier to migrate from CFS but I have to admit I don't have a lot of time currently so don't expect something before weeks (more or less)... sorry.
