### ISSUE TITLE
Does UFS handle multiple servers working with the same database?

### ISSUE THREAD

**Issue by Lavan** [jalik/jalik-ufs#16]
A bit of additional explanation:
I have two apps (admin console + client app) that connect to the same database instance. I currently use CollectionFS but there's an issue with CFS in that the server will crash quite frequently if two apps access the same database using CFS.

Have you tested something similar with UFS?

**Comment by jalik** [comment]
Hi, I haven't tested it, but if you only talk about access (reading) it should not be a problem, only concurrent writing are a problem in a shared environment.

**Comment by sebakerckhof** [comment]
@Lavan Did you test this out?

**Comment by Lavan** [comment]
Sorry, completely missed this. Even read only access would crash the server but the issue has been resolved since then.
