### ISSUE TITLE
Store fileId to other collection?

### ISSUE THREAD

**Issue by halallah** [jalik/jalik-ufs#18]
Hi, Im using GridFS how can I store fileId to other collection (autoform). in my situation I want to link my 'post collection'  to the uploaded image.

**Comment by jalik** [comment]
Hi, it depends of how you want to store the relation, but there is not "one way to do it", you choose how to do based on your needs.

1) If the file has only one post, then you save the **postId** in the **file** object :
```js

// Before uploading the file, add the fields you want
photo.postId = 'thePostId';

new UploadFS.Uploader({
                // This is where the uploader will save the file
                store: Meteor.photosStore,
                // The file data
                data: data,
                // The document to save in the collection
                file: photo
            }).start();
```

2) If the post has only one file, then you save the **fileId** in the **post** object :

```js
var upload = new UploadFS.Uploader({
                // This is where the uploader will save the file
                store: Meteor.photosStore,
                // The file data
                data: data,
                // The document to save in the collection
                file: photo,
                // The complete callback
                onComplete: function (file) {
                    console.log(file.name + ' has been uploaded');
                    // Link the file to the post
                    Posts.update('thePostId', { $set: { fileId: file._id }});
                }
            }).start();
```

I could go on and propose other solutions but it's not the goal, read the doc (it's actually very light but complete) and do it the way it'll be the best for your app.

**Comment by halallah** [comment]
Thanks for you explain @jalik, solved.
