### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#20]
**Error message**

W20151016-15:55:44.251(-4)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.1.9.z0bbxn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151016-15:55:44.252(-4)? (STDERR) 						throw(ex);
W20151016-15:55:44.252(-4)? (STDERR) 						      ^
W20151016-15:55:44.252(-4)? (STDERR) ReferenceError: _ is not defined
W20151016-15:55:44.252(-4)? (STDERR)     at new UploadFS.store.Local (packages/jalik_ufs-local/packages/jalik_ufs-local.js:21:1)
W20151016-15:55:44.252(-4)? (STDERR)     at is_admin (packages/mypack_biotools/collections.js:12:1)
W20151016-15:55:44.253(-4)? (STDERR)     at /Users/me/Documents/meteor/test/.meteor/local/build/programs/server/packages/mypack_biotools.js:271:4
W20151016-15:55:44.253(-4)? (STDERR)     at /Users/me/Documents/meteor/test/.meteor/local/build/programs/server/packages/mypack_biotools.js:749:3
W20151016-15:55:44.253(-4)? (STDERR)     at /Users/me/Documents/meteor/test/.meteor/local/build/programs/server/boot.js:242:10
W20151016-15:55:44.253(-4)? (STDERR)     at Array.forEach (native)
W20151016-15:55:44.253(-4)? (STDERR)     at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.1.9.z0bbxn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151016-15:55:44.254(-4)? (STDERR)     at /Users/me/Documents/meteor/test/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

**My application layout is like this**

main meteor app dir
--packages
----mypack:biotools
----mypack:manage-users

**meteor list**

blaze-html-templates  1.0.1
ecmascript            0.1.5
es5-shim              4.1.13
jquery                1.11.4
meteor-base           1.0.1
mobile-experience     1.0.1
mongo                 1.1.2
mypack:biotools       1.0.0+
mypack:manage-users   1.0.0+
session               1.1.1
standard-minifiers    1.0.1
tracker               1.0.9

**other package versions**

jalik:ufs@0.2.9
jalik:ufs-local@0.2.2
Meteor 1.2.0.2

**Package.js for mypack:biotools and mypack:manage-users contains**

api.use("underscore@1.0.4");
api.imply("underscore@1.0.4");

**Package.js for mypack:biotools contains**

api.use("jalik:ufs@0.2.9");
api.use("jalik:ufs-local@0.2.2");

**Comment by jalik** [comment]
Hi @firewater, I've added explicit dependencies to Underscore.js in the last versions of UFS packages, could you try and let me know if it resolved your problem ?

**Comment by jalik** [comment]
@firewater I actually think that it's maybe your package that throws the exception, have you added `api.use('underscore');` in the **package.js** ?

**Comment by firewater** [comment]
@jalik thank you for the quick reply. The latest version seems to fix the problem. I am encountering a different error now and will open a new issue.
