### ISSUE TITLE
Question: onFinishUpload vs onComplete ?

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#25]
Hi jalik, thanks for this helpful Meteor package. I have a question:

what is the difference between `onFinishUpload` and `onComplete` ?

Thanks!

**Comment by jalik** [comment]
The difference is just that `onFinishUpload()` is called on the store (server) which is the destination and `onComplete()` is called on the uploader (client) which is the source of the transfer, nothing more nothing less.
