### ISSUE TITLE
Return false to onRead should abort the request

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#28]
Throw an error as you describe in the README generate a response with 500 Internal Server Error.

If we can abort the request returning false we can reply the request with the correct status code and body before aborting without need throw an exception.

https://github.com/jalik/jalik-ufs/blob/1f4ddf8d7661a2226468edec982067248dfbf6ad/ufs-server.js#L157

**Comment by jalik** [comment]
Hi @rodrigok the version **0.3.4** has been released with a few changes including your request. The `onRead()` method is now used to **allow/deny** access to a file by returning **true/false**. Note that returning nothing is equivalent to returning **false** and returning false automatically calls the `end()` method on the `response`.

As you requested, it allows you to send a custom HTTP code using `response.writeHead(403);`.

**Comment by rodrigok** [comment]
Great news, thanks :smile:
