### ISSUE TITLE
stream never ends in copyTo

### ISSUE THREAD

**Issue by jalik** [jalik/jalik-ufs#31]
The new feature of `copyTo` available as an option in any store is buggy.

**Case 1** : The `copyTo` array contains one store which contains itself a `copyTo` with one store, so we have a cascade of copies, this case works !

**Case 2** : The `copyTo` array contains several stores with no cascade copies, this leads to errors on writing the original file and copies...

There seems to be a problem with streams that I don't master at all,  the `end` event of readstream is not called, so @rodrigok if you know someone that could help me to solve this it would be nice :)

https://github.com/jalik/jalik-ufs/blob/master/ufs-store.js#L174-L213

**Comment by jalik** [comment]
Alright, I battled during 2 days and I finally resolved the stream problem, it's now working like a charm. I just hope the way I chose is not greedy... basically I had to open a stream for each copy instead of reusing the same stream.

**Comment by rodrigok** [comment]
Great news @jalik, I saved this issue to replay ASAP but I didn't have time to look the code.

I'm very happy to see the evolution of this package, we are using a lot at Rocket.Chat.

Congrats.
