### ISSUE TITLE
AutoForm support?

### ISSUE THREAD

**Issue by brylie** [jalik/jalik-ufs#33]
The AutoForm package has a couple of competing file field solutions. It seems like the Jalik UploadFS package might be a good addition to the AutoForm field types, particularly as UploadFS has a progress indicator which is a [long-ago-requested feature for AutoForm-CFS](https://github.com/aldeed/meteor-cfs-autoform/issues/14).

What are your thoughts on packaging UploadFS, so that it can be used as a field type for AutoForm templates?

**Comment by jalik** [comment]
@brylie, I've never used AutoForm, so I don't know how it works and what I would have to do to propose what you want, but I am almost sure it could be a bridge package that brings UFS support to AutoForm.

Currently UFS is only one of my projects and I am trying to improve/maintain all my packages asap so I don't really have the time for your request, but if someone feels brave enought to create such a package I could help him, UFS is really easy to use, learn and modify so...

**Comment by krishaamer** [comment]
+1, would also love UFS for autoform, especially as it would make it automatically work for the http://orionjs.org admin package.

**Comment by jalik** [comment]
I am sorry, I don't use AutoForm so I can't help, but if someone feels brave enough to contribute, I would recommend to create another package as this could be seen as an addon to the core of UploadFS.

**Comment by JulianKingman** [comment]
I've got a solid start on an autoform component. I just got this working today (based on the UFS example), so use at your own risk:
https://github.com/DesignmanIO/meteor-autoform-ufs

**Comment by jalik** [comment]
@JulianKingman Thank you for your contribution, I am sure that it will be much appreciated by AutoForm users, are you OK if I put a link to your package in the UploadFS documentation ?

**Comment by JulianKingman** [comment]
Sure, go ahead :)

**Comment by droka** [comment]
I also made a package, for this. Started out from ostrio:files, and rewritten it to use jalik:ufs for file upload.
Works pretty well. UI is not configurable ATM (uses the bootstrap classes). But someone can fork it if needed.
Here is the package: https://github.com/droka/meteor-autoform-ufs/
