### ISSUE TITLE
Resize before upload?

### ISSUE THREAD

**Issue by skemb321** [jalik/jalik-ufs#35]
Hi I wonder if we can use uploadFS to resize the image before uploading?

It would be a very great feature specially for mobile apps.

**Comment by jalik** [comment]
Hi @skemb321 , of course you can do that, but image manipulation on client side is not very reliable as it would not work for all browsers. I haven't tested the code below but it should look like this at the end, let me know if it works or what you did to make it work, Thank you ;-)


    Template.upload.events({
    'change input[type=files]': function (ev) {
        var files = ev.target.files;
        var img = document.createElement('img');

        for (var i = 0; i < files.length; i += 1) {
            var file = files[i];

            (function (file) {
                var reader = new FileReader();
                reader.onload = function (ev) {
                    img.src = ev.target.result;

                    // Use canvas to resize image
                    var canvas = new HTMLCanvasElement();
                    canvas.width = img.width;
                    canvas.height = img.height;
                    // Resize to 128x128
                    var ctx = canvas.getContext('2d');
                    ctx.drawImage(img, 0, 0, 128, 128);
                    // Get data url of the resized image
                    var dataURL = canvas.toDataURL('image/jpeg');
                    // Convert data url to array buffer for UFS
                    // See the code of the dataURLToBlob function here : https://github.com/ebidel/filer.js/blob/master/src/filer.js#L137
                    var blob = dataURLToBlob(dataURL);
                    // Prepare file document
                    var photo = {
                        name: file.name,
                        size: file.size,
                        type: file.type
                    };
                    // Upload the resized image
                    var upload = new UploadFS.Uploader({
                        store: PhotosStore,
                        data: blob,
                        file: photo,
                        onError: function (err) {
                            console.error(err);
                        }
                    });
                    upload.start();
                };
                reader.readAsDataURL(file);
            })(file);
        }
    }
});

**Comment by skemb321** [comment]
nice, thank!  Will try this out @jalik

**Comment by mihirjain1930** [comment]
How can we find the dimensions of the image before uploading?

**Comment by jalik** [comment]
@mihirjain1930 I do not provide help for other thing than **UploadFS**, this kind of question has a lot of answers on stackoverflow : http://stackoverflow.com/questions/623172/how-to-get-image-size-height-width-using-javascript
Thank you for you understanding.
