### ISSUE TITLE
Add a config parameter to simulate slow transfer

### ISSUE THREAD

**Issue by jalik** [jalik/jalik-ufs#4]
Using `Meteor._sleepForMs(number)` in Meteor.methods, we can simulate a slow transfer.
For testing purposes, this feature would be available via `UploadFS.config.testing = true` or anything like that.

**Comment by rodrigok** [comment]
Maybe
```
UploadFS.config.writeDelay = 200;
```
and
```
UploadFS.config.readDelay = 200;
```

**Comment by jalik** [comment]
@rodrigok, thank you for your proposition, I will however wrap them in a "simulation" namespace (or whatever the name), this way it won't conflict with a possibly future option named like that.
But I agree, two parameters are better than one.
