### ISSUE TITLE
Images not displayed in production (Scalingo)

### ISSUE THREAD

**Issue by kokokenada** [jalik/jalik-ufs#41]
I'm using alik:ufs and jalik:ufs-gridfs for Avatar images in an Angular 2 app and it is working fine in my development environment.  (Source code is at https://github.com/kokokenada/for-real-cards)  I have the app deployed to scalingo.  (http://for-real-cards.scalingo.io/) The images URLs are not working. (The images don't show up in the app nor entering the URL directly in the browser.)  The Mongo collections all seem to be populated.

Not sure if this is an issue or a question and if it is an issue where the issue is.  Are there any configuration requirements for production? (Didn't see any in the readme.)

**Comment by jalik** [comment]
Hi, check if there are errors in logs, are you transforming images on read/write ? try to open the file using the URL to see what is the error (with your browser/dev console, or curl).

Maybe it's a configuration problem. There is not any difference between prod and dev because UFS just cannot know if you are in dev or prod.

**Comment by kokokenada** [comment]
Thanks for the reply.  The logs are completely clean. (Except when I paste the URL into a browser window there is this warning, but it looks normal):
````
Resource interpreted as Document but transferred with MIME type image/png: "https://for-real-cards.scalingo.io/ufs/avatar-medium/x72qMfLGxwfdYvkoW/Business%20400x400.png".
Navigated to https://for-real-cards.scalingo.io/ufs/avatar-medium/x72qMfLGxwfdYvkoW/Business%20400x400.png
````
I've been picking at the problem to no avail...

It works fine running locally with the --production flag.  

I've added BrowserPolicy.content.allowOriginForAll(), in a Meteor.startup block as well.  Still had the problem.

I looked carefully at the network log and the URL returns 200 status:
````
Request URL:https://for-real-cards.scalingo.io/ufs/avatar-medium/x72qMfLGxwfdYvkoW/Business%20400x400.png

Request Method:GET
Status Code:200 OK
Remote Address:94.125.104.17:443

Response Headers
Connection:keep-alive
Content-Encoding:gzip
Content-Type:image/png
Date:Fri, 10 Jun 2016 23:11:15 GMT
Server:nginx
Transfer-Encoding:chunked

Request Headers
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:for-real-cards.scalingo.io
Pragma:no-cache
Referer:https://for-real-cards.scalingo.io/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
````

I've been in touch with the Scalingo guys who have been responsive (and very helpful resolving other hiccups I had) but seem to be out of ideas on this one. (As am I.) 

Debugging ideas would be appreciated.

**Comment by kokokenada** [comment]
Thanks for your comment about transforming images.   The URL for the original image does actually work.  It's only when I try to access the transformed images that the failure occurs.  The answer was obvious, after bit more digging.  "gm" needs to be installed in the deployment environment.

However, I have console logging on at the onFinishUpload and the resulting file object seems to be fine with a well formatted URL. So, perhaps there's a problem with the package in that it could have reported an error?

**Comment by kokokenada** [comment]
Just to document the fix from the Scalingo perspective, gm is not installed by default, but it is easily added by following the instructions here: http://doc.scalingo.com/internals/graphicsmagick-buildpack.html

**Comment by jalik** [comment]
@kokokenada, I was thinking of that kind of issue, I faced the same problem on digital ocean, that's why I asked if you were using the transform methods (with gm or another lib). I am glad you figured it out.

**Comment by kokokenada** [comment]
Thanks again. The silent failure is of concern.  It would have saved me an hour or two if it said "gm not found" in the server console.  I was looking at the transform write source code, and perhaps it's more of an issue in the "gm" node library (npm install gm) than UploadFS.  Your thoughts?  My app, which was blissfully unaware of the failure, looks like:
````
export const AvatarMediumStore = new UploadFS.store.GridFS({
  collection: AvatarMediumCollection,
  name: 'avatar-medium',
  transformWrite(from, to, fileId, file) {
    gm(from, file.name)
      .resize(250, 250)
      .gravity('Center')
      .extent(250, 250)
      .quality(100)
      .stream()
      .pipe(to);
    console.log('finished(?) transform medium')
    console.log(file)
  },
  onFinishUpload: (file)=>{
    console.log('finished upload medium')
    console.log(file)
    Meteor.users.update({_id: file.userId}, {$set: {'profile.avatar-medium': file.url}})
  },

});
export const AvatarThumbsStore = new UploadFS.store.GridFS({
  collection: AvatarThumbCollection,
  name: 'avatar-thumbs',
  transformWrite(from, to, fileId, file) {
    gm(from, file.name)
      .resize(50, 50)
      .gravity('Center')
      .extent(50, 50)
      .quality(75)
      .stream()
      .pipe(to);
    console.log('finished(?) transform thumb')
    console.log(file)
  },
  onFinishUpload: (file)=>{
    console.log('finished upload thumb')
    console.log(file)
    Meteor.users.update({_id: file.userId}, {$set: {'profile.avatar-thumb': file.url}})
  },

});
export const AvatarOriginalStore = new UploadFS.store.GridFS({
  collection: AvatarOriginalCollection,
  name: 'avatar-original',
  onFinishUpload: (file)=>{
    console.log('finished upload original')
    console.log(file)
    Meteor.users.update({_id: file.userId}, {$set: {'profile.avatar-original': file.url}})
  },
  filter: new UploadFS.Filter({
    contentTypes: ['image/*']
  }),
  copyTo: [
    AvatarMediumStore,
    AvatarThumbsStore
  ]
});

````

**Comment by jalik** [comment]
@kokokenada I forget to answer about that sorry...

Have you defined a custom `Store.onWriteError()` ?
Is so, the callback is called with these args : `(err, fileId, file)`
So you would need to add a `console.error(err.message)` to output the error.

If it's not that, maybe it's maybe the following :
In `store.copy()`, make sure to handle the error in the callback : https://github.com/jalik/jalik-ufs/blob/master/ufs-store.js#L150-L152
