### ISSUE TITLE
how to use onRead for securing file access?

### ISSUE THREAD

**Issue by sbalbalosa** [jalik/jalik-ufs#42]
```
  collection: Avatars,
  name: 'Avatars',
  onRead: (fileId, file, request, response) => {
    response.writeHead(403);
    return false;
  },
```

Given the code above I would expect that this would disallow all file access to avatars instead I received an error in the console because of the response.writeHead method.
 
(STDERR) Error: Can't set headers after they are sent.

**Comment by jalik** [comment]
Hi @sbalbalosa, this is exactly what it is supposed to do, are you sure you don't have any error in the console other than the one you mentionned ?

I tried to do the same thing and it works fine on the https://github.com/jalik/ufs-example test project.

**Comment by sbalbalosa** [comment]
@jalik recently I noticed that the package I installed was outdated, I updated the package and now it works fine. I think it is because of outdated dependency for jalik/jalik-ufs-gridfs this is the adapter that I'm using.

**Comment by jalik** [comment]
@sbalbalosa good news that you solved it, also don't forget to install dependencies like gm and everything should works like a charm.
