### ISSUE TITLE
Can't upload picture from Cordova Camera

### ISSUE THREAD

**Issue by kokokenada** [jalik/jalik-ufs#43]
I've tried various approaches to try to get this to work.  FileReader doesn't seem to work when I try to open the file returned by the Camera (perhaps due to permissions???).

I thought UploadFS.importFromURL might work, but it returns the error "errorClass {error: 500, reason: "Cannot call method 'replace' of undefined", details: undefined, message: "Cannot call method 'replace' of undefined [500]", errorType: "Meteor.Error"}"

The code is something like:

````
Camera.getPicture(options).then(
     (imageFile)=> {
        imageFile=WebAppLocalServer.localFileSystemUrl(imageFile);  // As per https://guide.meteor.com/mobile.html
        var attributes = { name: 'Camera Picture', description: 'Picture take from device camera' };

        UploadFS.importFromURL(imageFile, attributes, collection, function (err, fileId) {
           if (err) {
````

It would be great to have a documentation example on how to upload a camera picture.  I would imagine it's a common scenario and I've done a lot a searching and none of the examples seem to apply to Meteor 1.3.  Any pointers would be much appreciated.

**Comment by jalik** [comment]
Hi @kokokenada, have you tested all solutions described in https://guide.meteor.com/1.3-migration.html#mobile ?

As the doc says, `Camera.getPicture()` returns either a **base64** string representing the file or the **URI** of the file. Be sure to know what it returns before passing it to the `UploadFS.importFromURL()` method.

The error you mentioned seems to happen because you did not define the "name" attribute (which is optional), so UFS uses the URL to get the name, that's why `replace()` is called on the url, but the value of your `imageFile` variable is `undefined`.

I am sorry but as I can see, it does not rely on UFS but on your code.

**Comment by kokokenada** [comment]
Thanks @jalik for the response.  I have managed to get something working using UploadFS.Uploader.  I had a lot of problems with FileReader.  For some unknown reason onload was not being called.  I could step through my code and see it being set and I saw Angular seemed to wrapping the calls some how.  I had to add a work around:
````
 var reader:any = new FileReader();
 reader = reader.__zone_symbol__originalInstance; // Why on earth do I need to do this???
  reader.onload = (ev:any)=> {
            console.log('reader.onload')
````
I'm using rc1 and ionic - not sure if that's relevant.  I will upgrade soon and see what happens.  I'll put together a complete example when I figure out how not use the work around.  In the meantime, what I managed to make work is here: https://github.com/kokokenada/for-real-cards/blob/ionic-ui/imports/for-real-cards/edit-user-profile/edit-user-profile.ionic.ts 

Regarding the UploadFS.importFromURL approach, you can see in my code above, I was setting the name  attribute (or do I misunderstand?).  My thinking in trying that approach is that, as of Meteor 1.3, you access files via a web server (https://guide.meteor.com/mobile.html)

**Comment by boomfly** [comment]
You can't use UploadFS.importFromURL method because import logic is implemented on the server side, and for example if you get a url type http://localhost:12480, and then the server will attempt to download from this address. DATA_URL is alternative, but it have some bugs in v 0.6.1. I think there needs config option to choose between HTTP or Meteor methods upload

**Comment by domiko** [comment]
@jalik , can we see an example of how you would import an image obtained straight from a (mobile's) camera?

**Comment by jalik** [comment]
@domiko, I haven't tested the package with Cordova, I'll to find some time to investigate that way.

**Comment by kokokenada** [comment]
The link above (https://github.com/kokokenada/for-real-cards/blob/ionic-ui/imports/for-real-cards/edit-user-profile/edit-user-profile.ionic.ts) leads to a working example with Cordova.  The packages are way behind and I had to put in a strange work around.  A clean Cordova example would be very much appreciated.  It hosed hours and hours trying to get as far as I did...

**Comment by domiko** [comment]
Hey guys.
I was finishing something else, thanks for the feedback and sorry for the delay.

This works for me (es6):
```javascript
    demoGetPicture() {

        MeteorCameraUI.getPicture({ width: 640, height: 480 }, (err, dataURL) => {

            const blob = this.dataURLToBlob(dataURL);
            blob.name = 'DEMO';
            const file = _.pick(blob, 'name', 'type', 'size');

            console.log('blob', blob, blob instanceof Blob);

            const upload = new UploadFS.Uploader({
                data: blob,
                file,
                store: ImagesStore,
                onError: err => {
                    console.log('ERR', err);
                },
                onComplete: () => {
                    console.log('OK');
                }
            });

            upload.start();
        });
    }
```

//Dominique

**Comment by jalik** [comment]
Thank you @domiko, I hope it will help people with Cordova issues.
@kokokenada could you test and confirm that the code @domiko gave is working for you ?

**Comment by kokokenada** [comment]
Finally getting back to this. @domiko - thanks for the suggestion.  What is your implementation of dataURLToBlob?

**Comment by domiko** [comment]
Hey @kokokenada 

You can actually replace:

```javascript
const blob = this.dataURLToBlob(dataURL);
```

With:

```javascript
const blob = MeteorCameraUI.dataURIToBlob(dataURL);
```

Regards

**Comment by domiko** [comment]
For reference, here is my implementation:
`onStar`, `onError` and `onComplete` are functions

```javascript
Util.getPicture = function (width, height, onStart, onError, onComplete) {

    MeteorCameraUI.getPicture({ width: width, height: height }, (err, dataURL) => {

        if (err) return onError(err);

        const blob = MeteorCameraUI.dataURIToBlob(dataURL);
        blob.name = 'default';
        const file = _.pick(blob, 'name', 'type', 'size');

        //console.log('blob', blob, blob instanceof Blob);

        const upload = new UploadFS.Uploader({
            data: blob,
            file,
            store: ImagesStore,
            onError: (err) => {
                onError(err);
            },
            onComplete: (file) => {
                let file2 = _.pick(file, '_id', 'type', 'size', 'name', 'identify');
                file2.url = file.url.replace(Meteor.absoluteUrl(), '/');
                onComplete(file2);
            }
        });

        onStart();

        upload.start();
    });
};
```

**Comment by kokokenada** [comment]
Thanks.  I got it to work. (In the sample above, change file, to file:file.)  A PR for the Readme for this would be a good idea!
