### ISSUE TITLE
Usage with angular2-meteor: Cannot find module 'meteor/jalik:ufs'

### ISSUE THREAD

**Issue by janus-reith** [jalik/jalik-ufs#46]
This is probably not directly related to jalik-ufs, but  I am unable to import this module properly.
I get the error `Cannot find module 'meteor/jalik:ufs'` in the console log.

Webstorm highlighst `import { UploadFS } from 'meteor/jalik:ufs';` in my code, stating that it can't resolve the symbol UploadFS and the directory meteor in `meteor/jalik:ufs`.

What am I missing here? 
I tried to implement UploadFS like described [here on the angular-meteor website](https://www.angular-meteor.com/tutorials/socially/angular2/handling-files-with-collectionfs)

**Comment by jalik** [comment]
Hi @janus-reith, honestly I am not using Angular so I can't really help you on this side but if you have installed the package and imported it, you should be able to use it without problem.
Try to update Meteor, you could also download the UploadFS souce code and put it inside you project's directory under a folder like `/path/to/yourproject/packages/ufs`. This will force Meteor to use the package locally instead of downloading it.

**Comment by janus-reith** [comment]
Thanks for your help, tried it with the UFS Source.
While meteor recognizes the local package, the issue persists:
```
collections/images.ts (3, 26): Cannot find module 'meteor/jalik:ufs'.
collections/methods.ts (2, 26): Cannot find module 'meteor/jalik:ufs'.
collections/methods.ts (18, 33): Property 'result' does not exist on type 'EventTarget'.
collections/methods.ts (5, 36): Cannot find name 'File'.
collections/methods.ts (12, 24): Cannot find name 'FileReader'.
collections/methods.ts (15, 26): Cannot find name 'ProgressEvent'.
```

**Comment by jalik** [comment]
Are you using another kind of syntax ? I see that your files are ending with `.ts`.
Maybe it's related to code compilation ? I am using standard JavaScript.
Could you post the code at lines mentioned in the errors ? (images.ts and methods.ts).
Thank you.

**Comment by janus-reith** [comment]
I am using Typescript/typings module.
I am starting to think that my issues here are actually just warnings related to Typescript as it is missing some kind of declarations(or whatever, I am quite new to TypeScript)

However, this is the code:

images.ts:
```
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { UploadFS } from 'meteor/jalik:ufs';

export const Images = new Mongo.Collection<Image>('images');
export const Thumbs = new Mongo.Collection<Thumb>('thumbs');

function loggedIn(userId) {
    return !!userId;
}

Thumbs.allow({
    insert: loggedIn,
    update: loggedIn,
    remove: loggedIn
});

Images.allow({
    insert: loggedIn,
    update: loggedIn,
    remove: loggedIn
});

export const ThumbsStore = new UploadFS.store.GridFS({
    collection: Thumbs,
    name: 'thumbs'
});

export const ImagesStore = new UploadFS.store.GridFS({
    collection: Images,
    name: 'images',
    filter: new UploadFS.Filter({
        contentTypes: ['image/*']
    }),
    copyTo: [
        ThumbsStore
    ]
});
```

methods.ts:
```
import {Meteor} from 'meteor/meteor';
import { UploadFS } from 'meteor/jalik:ufs';
import { ImagesStore } from './images';

export function upload(sourceFile: File, resolve?: Function, reject?: Function) {
    // pick from an object only: name, type and size
    const file = {
        name: sourceFile.name,
        type: sourceFile.type,
        size: sourceFile.size,
    }
    const reader = new FileReader();

    // handle progress
    reader.onload = (ev: ProgressEvent) => {
        if (ev.type === 'load') {
            const upload = new UploadFS.Uploader({
                data: ev.target.result,
                file,
                store: ImagesStore,
                onError: reject,
                onComplete: resolve
            });

            upload.start();
        } else if (ev.type === 'error') {
            throw new Error(`Couldn't load file`);
        }
    };
    // as ArrayBuffer
    reader.readAsArrayBuffer(sourceFile);
}
```

**Comment by jalik** [comment]
@janus-reith if you're using the last version `0.6.1` of UploadFS, you should change your code following this : https://github.com/jalik/jalik-ufs#breaking-changes

Also, is the `methods.ts` file accessible to the client or server ? because `FileReader` is not available on server side I think.

I still don't understand, do you have warnings or errors ? is the code working ? Can you upload files ?
I need to be sure that it's not a bug, you know. ;)

**Comment by janus-reith** [comment]
Sadly I am still trying to figure that out and can't give an exact answer,, meteor handles the client-server bindings and I'm still learning how to use it :)

I stopped implementing the code at the point when i got these errors, I will finish it and give feedback if it works as intended.

Thank you for your fast responses!

**Comment by janus-reith** [comment]
I am sure now that the output is a warning and not an error and related to Typescript.
Still I would really appreciate your help here, as I'm somehow unable to get my code compatible to 0.6.2.
I hope this is not too much to ask.

console.log(FileStore.getPath()) outputs "/uploads/files" in the browser console as intended,
console.log(FileStore.getFilePath(sourceFile)); outputs undefined.
I also can't find a folder called /uploads/files or the file I uploaded.


/both/collections/files.ts:
```
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { UploadFS } from 'meteor/jalik:ufs';

export const Files = new Mongo.Collection<Image>('files');

export const FileStore = new UploadFS.store.Local({
    collection: Files,
    name: 'files',
    path: '/uploads/files',
    mode: '0744', // directory permissions
    writeMode: '0744', // file permissions
});
```

/both/collections/methods.ts:
```
import {Meteor} from 'meteor/meteor';
import { UploadFS } from 'meteor/jalik:ufs';
import { FileStore } from './images';

export function upload(sourceFile: File, resolve?: Function, reject?: Function) {
    // pick from an object only: name, type and size
    const file = {
        name: sourceFile.name,
        type: sourceFile.type,
        size: sourceFile.size,
    }
    const reader = new FileReader();

    // handle progress
    reader.onload = (ev: ProgressEvent) => {
        if (ev.type === 'load') {
            const upload = new UploadFS.Uploader({
                data: ev.target.result,
                file,
                store: FileStore,
                onError: reject,
                onComplete: resolve
            });

            upload.start();
        } else if (ev.type === 'error') {
            throw new Error(`Couldn't load file`);
        }
    };
    console.log(FileStore.getPath());
    console.log(FileStore.getFilePath(sourceFile));
}
```

relevant part of /client/imports/ng2fupload/ng2fupload.component.html:
 ```
<div fileDrop
    [ngClass]="{'file-is-over': fileIsOver, 'file-uploading': uploading}"
    (fileOver)="fileOver($event)"
    (onFileDrop)="onFileDrop($event)">
    <div>Drop an image to here</div>
</div>
```
/client/imports/ng2fupload/ng2fupload.component.ts:
```
import { Component } from '@angular/core';
import { MeteorComponent } from 'angular2-meteor';
import { FileDropDirective } from 'angular2-file-drop';
import template from './ng2fupload.component.html';
import { upload } from '../../../both/collections/methods';

@Component({
    selector: 'fuploadcard',
    template,
    directives: [FileDropDirective]
})
export class ng2FileUploadComponent {
    public fileIsOver: boolean = false;
    public uploading: boolean = false;

    constructor() {}

    public fileOver(fileIsOver: boolean): void {
        this.fileIsOver = fileIsOver;
    }

    public onFileDrop(file: File): void {
        console.log('Got file');
        this.uploading = true;

        upload(file, (result) => {
            this.uploading = false;
        }, (error) => {
            this.uploading = false;
            console.log(`Something went wrong!`, error);
        });
    }
}

```

**Comment by JohannesMerkt** [comment]
@janus-reith what is the solution to this problem? I have tried coping the source files in packages/ufs but it makes no difference I am also using meteor with angular 2

**Comment by jalik** [comment]
@JohannesMerkt please provide more details if your issue is the same and be sure to read the doc to understand how the package works.

**Comment by JohannesMerkt** [comment]
I was following the Meteor Angular 2 Socially tutorial here: https://angular-meteor.com/tutorials/socially/angular2/files-and-uploadfs 

It is a bit tricky, because  since Meteor Atmosphere does not provide a typescript declaration for uploadFS and this causes Cannot find module 'meteor/jalik:ufs' error. In that tutorial they solve the error very late in the tutorial and I didn't see that. 

So everthing is working now

**Comment by jalik** [comment]
@JohannesMerkt I cannot help you with TypeScript but I am glad you found the solution.

**Comment by kamoroso94** [comment]
If you're also following the [WhatsApp Clone with Ionic 2 and Meteor CLI tutorial](https://angular-meteor.com/tutorials/whatsapp2/meteor/setup), you need to include this [declarations.d.ts](https://github.com/Urigo/Ionic2-MeteorCLI-WhatsApp/blob/master/declarations.d.ts) file in your project root directory.

**Comment by ManyRouc** [comment]
@JohannesMerkt could you please tell me how they solved it ? i can't get past it ...

**Comment by jalik** [comment]
@ManyRouc please try those three require statements, and tell us if something worked.
`const UploadFS = require('meteor/jalik:ufs');`
or
`const UploadFS = require('meteor/jalik:ufs').default;`
or
`const UploadFS = require('meteor/jalik:ufs').UploadFS;`

**Comment by jalik** [comment]
Note: you could also console.log() the imported object to better understand what is wrong.
Like :
```
import all from 'meteor/jalik:ufs';
console.log(all);
```
