### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by FlawaCLV** [jalik/jalik-ufs#48]
Just installed your package on Meteor 1.3.4.2 with `meteor add jalik:ufs jalik:ufs-local` but it crashes my entire app as it doesn't have UploadFS globally. Its `undefined`.

Any ideas ?

**Comment by jalik** [comment]
Hi @FlawaCLV, I have several projects with UploadFS, I don't have this problem, did you follow the doc ? you can also download and run the [UFS-Example](https://github.com/jalik/ufs-example) project to see how it's implemented in an app. Tell me if you solved it.

**Comment by jalik** [comment]
On server side, a simple `import` should be enough.
If you are trying to use it on client side :
```js
import {UploadFS} from 'meteor/jalik:ufs';
window.UploadFS = UploadFS;
```

**Comment by jalik** [comment]
Hi @FlawaCLV did you solved your problem ?

**Comment by FlawaCLV** [comment]
Hey @jalik sorry I was in holidays ;)

I've updated to the latest version of meteor `1.4.0.1`and everything seams to work now without importing anything.
