### ISSUE TITLE
Add PassThrough to allow user to modify file while streaming (read and write)

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#5]
CollectionFS has this option, what do you think about it?

**Comment by jalik** [comment]
If you are talking about modifying an file on writing, you can do it by using the **transform** option when creating a store :
```js
Meteor.photosStore = new UploadFS.store.Local({
    collection: Meteor.photos,
    name: 'photos',
    path: '/uploads/photos',
    filter: new UploadFS.Filter({
        maxSize: 1024 * 1000,
        contentTypes: ['image/*'],
        extensions: ['jpg', 'jpeg', 'png']
    }),
    // Resize photos
    transform: function (readStream, writeStream, fileId) {
        // imagemagick-native
        readStream.pipe(im().resize('400x400').quality(90)).pipe(writeStream);
    
        // imagemagick-streams
        //readStream.pipe(imagemagick.streams.convert({
        //    quality: 75,
        //    width: 400,
        //    height: 400
        //})).pipe(writeStream);
    
        // GM
        //var gm = Npm.require('gm');
        //gm(readStream, fileId + '.png').resize('48', '48').stream().pipe(writeStream);
    
        // RAW
        //readStream.pipe(writeStream);
    }
});
```
Thus, I fail creating thumbnails using other lib then **imagemagick-native**...

If you're talking about modyfing a file when reading, I did not provide an option for the moment, it should come in next releases (not so far).

**Comment by jalik** [comment]
@rodrigok, I am facing a problem with the **transformRead()** method, if you have an idea : 
http://stackoverflow.com/questions/31759268/how-to-create-a-temporary-write-stream

**Comment by rodrigok** [comment]
Are you talking about https://nodejs.org/api/stream.html#stream_class_stream_passthrough?
