### ISSUE TITLE
Compatible with meteor 1.4

### ISSUE THREAD

**Issue by mrphu3074** [jalik/jalik-ufs#50]
Hi,

Today i just updated to release 1.4. Your great package have an issue (small) but it throw error. LoL.
```
I20160726-17:30:03.455(7)? Exception in callback of async function: TypeError: Cannot read property 'length' of null
I20160726-17:30:03.456(7)?     at writeOrBuffer (_stream_writable.js:267:41)
I20160726-17:30:03.456(7)?     at WriteStream.Writable.write (_stream_writable.js:214:11)
I20160726-17:30:03.457(7)?     at packages/jalik:ufs/ufs-server.js:92:16
I20160726-17:30:03.457(7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:1
```
This is exception that i got.

thanks,

**Comment by mitjade** [comment]
+1

**Comment by jonycfu** [comment]
+1 
Also running Meteor 1.4
Awesome package :-)

**Comment by wollardj** [comment]
👍  Samesies...
Meteor `1.4` + very awesome package 😄

**Comment by ansaries** [comment]
yeah its throwing this error and not uploading the file...

**Comment by wollardj** [comment]
@ansaries yep

**Comment by jalik** [comment]
Sorry all for the late answer, I merged @wollardj 's Pull Request and tested the package, it seems to be fine now. Thanks for the great feedbacks. Happy coding !
