### ISSUE TITLE
The permissions seems to be undefined

### ISSUE THREAD

**Issue by sbalbalosa** [jalik/jalik-ufs#51]
import { UploadFS } from 'meteor/jalik:ufs';
console.log(UploadFS.Permissions); // this is undefined

Looking at the tutorial there seems to be a new way of setting up permissions so I'm trying to migrate my code to this updated one but I wasn't able to progress since the permissions property is undefined,

Is there something that I missed out?

I recently updated to 1.4 and also these packages:
jalik:ufs                     0.6.1  Base package for UploadFS
jalik:ufs-gridfs              0.1.1  GridFS store for UploadFS

**Comment by jalik** [comment]
Hi @sbalbalosa, I am sorry, it was a typo error in the doc, I fixed the README, you have to use `UploadFS.StorePermissions` instead of `UploadFS.Permissions` .
Thank you for reporting.

**Comment by sbalbalosa** [comment]
@jalik Thanks for the info, great package update by the way
