### ISSUE TITLE
Post using localhost instead of IP where server resides.

### ISSUE THREAD

**Issue by ardwyn** [jalik/jalik-ufs#53]
Using code from the examples, when I try and upload an image it attempts to use localhost instead of the IP where the server resides for POST.  Am I wrong in thinking this is causing the failure?  I'm getting ERR_CONNECTION_REFUSED @ ufs-uploader.js:369
I am accessing the meteor server via a web browser on one machine and hosting meteor server on another on a local network.

**Comment by ardwyn** [comment]
figured it out I was running as localhost on starting meteor.  Fixed by using --port <IP>:<PORT> sorry to bother.

**Comment by jalik** [comment]
Hi @ardwyn no problem, if someone faces the same problem, he'll have the solution ;)
