### ISSUE TITLE
Doesn't seem to work on IOS

### ISSUE THREAD

**Issue by ardwyn** [jalik/jalik-ufs#54]
I get the file menu and select file, but it never uploads.  I don't currently have a way to check console on iphone/ipad.  Anyone else had this trouble?  Have tested on android tablet and it works there and on PC.

More info: using filesystem to write to, no cloud.

**Comment by Sphinxxxx** [comment]
+1
Sometimes, the first attempt doesn't initiate an upload, and I have to select the file a second time.

**Comment by ardwyn** [comment]
I've tried multiple times, no dice.  Any idea what causes the failure?  Love this package, but it failing on IOS is killing me.  And I don't have a way to test the failpoint.  Early on I had it fail occasionally on an android tablet, but I cleaned up a lot on my end (new to meteor and this level of javascript) and now it seems to be much more stable.

**Comment by jalik** [comment]
@ardwyn I am sorry I don't own Apple devices, and so cannot test it on these hardwares.
Also, mobile platform is not my priority for this project, but since it should not require a lot of work to make it compatible I'll try to help if I can.

**Comment by Sphinxxxx** [comment]
FWIW, the problem with the first attempt missing was on a Windows 10 pc, using the latest Chrome.

**Comment by xunyangjian** [comment]
[https://github.com/jalik/jalik-ufs/blob/master/ufs.js#L79-L89](url),
at  IOS , add event listener on a new  element is not work.

Change:
[let img = document.createElement('input');] =>let img = document.getElementById（"a hide elemetn "）；

**Comment by xunyangjian** [comment]
https://github.com/jalik/jalik-ufs/pull/60/files

**Comment by jalik** [comment]
@ardwyn @Sphinxxxx  Could you upgrade UFS to the 0.6.3 version and tell me if it solves your problem ? Thank you. You should also give a look to the mobile testing doc.
