### ISSUE TITLE
Dynamically set path localFS?

### ISSUE THREAD

**Issue by ardwyn** [jalik/jalik-ufs#56]
Is there a way to do this?  I've tried making path into a function but it fusses at me about it not being a string, even though I returned a string from the function.  Been looking around in the code, but it's above me :)

**Comment by jalik** [comment]
Hi @ardwyn, why do you want to do that ?
Are you talking about the `path` option of the `LocalStore` ?
This path cannot be dynamic, at least I don't see why it should be...

You can pass a `String` variable as the path, but once the store is created the path cannot be changed.

If you need several destinations you must create one store for each.
So if you have :
`/uploads`
`/uploads/photos`
`/uploads/files`

You must create a `FileStore` + a `PhotoStore`, this is a little more code than using a single store but it allows to manage files with better precision.

**Comment by ardwyn** [comment]
Ahhh, I think I understand now.  The path is permanent by necessity so the images can be served?  I suppose I could copy the files into the filesystem structure I've been asked for and keep the ones uploaded to this Store as is.  Duplication, but shouldn't be too much of an issue.  I've been asked to maintain a directory structure eg: state/city/site/...so the images can be looked up outside the app with ease as well.

**Comment by jalik** [comment]
Okay, it's true that if you have to manage a lot of directories it can be complicated but I don't see other solution for now.

Just one thing, files must be named with the databade `{_id}.{extension}`.

**Comment by ardwyn** [comment]
Thank you!  Resolved.

**Comment by maxwarch** [comment]
Hi jalik,
how do you handle a lot of files in one dir ? So, i thought i can create a structure based on date (like wordpress) but, if i can't change the path dynamically, i can't do something like this.
I saw this http://stackoverflow.com/a/466596

Thanks.

**Comment by jalik** [comment]
@maxwarch can you explain your problem ?

What do you want exactly :
- a custom URL path ?
- or a custom physical path (directories) ?

To answer your first question, I don't see a problem to put all files in one dir since modern file systems support a huge quantity of files.

If you want to create sub-directory, you can create a store that points to `/uploads/files` and another one that points to `/uploads/files/pdf`.

**Comment by maxwarch** [comment]
I want these 2 solutions ;)
So, i want to create a "virtual" files structure based on physical files structure with directories that i explained in my previous post. I don't care about what type of file, i don't need to put image in image dir or pdf in pdf dir...
I read that too much files in one dir decrease performance for search
