### ISSUE TITLE
Really basic example

### ISSUE THREAD

**Issue by muscaiu** [jalik/jalik-ufs#61]
I've been reading the documentation and poking in `ufs-example` in order to implement into my project. 
There seems to be allot of parts that need to be included and i'm not sure which part of the code goes in the server or in the collection or in the store. 

Can someone post a really simple example of an upload button with a link to the uploaded file?
I basically want to see which part goes in what folder.
Thank you.

**Comment by jalik** [comment]
Hi @muscaiu in order to upload a file with UploadFS, you need :
- a store on the **client/server**
- a collection used by the store on the **client/server**
- an uploader on the **client**

That's all, quick & easy, UFS-Example should be enough to understand how it works.
