### ISSUE TITLE
Use UploadFS with Autoform

### ISSUE THREAD

**Issue by muscaiu** [jalik/jalik-ufs#63]
Is there any example of using UploadFS with [Autoform](https://github.com/aldeed/meteor-autoform)?

**Comment by jalik** [comment]
Hi @muscaiu, @JulianKingman made a plugin (issue #33), check it : https://github.com/DesignmanIO/meteor-autoform-ufs

**Comment by droka** [comment]
I also made a package, for this. Started out from ostrio:files, and rewritten it to use jalik:ufs for file upload.
Works pretty well. UI is not configurable ATM (uses the bootstrap classes). But someone can fork it if needed.
Here is the package: https://github.com/droka/meteor-autoform-ufs/
