### ISSUE TITLE
Separate Browse and Upload buttons

### ISSUE THREAD

**Issue by muscaiu** [jalik/jalik-ufs#65]
I'm using this working template to upload multiple files and display the links like in the provided example:

>     <template name="uploadForm">
>         <button class="btn btn-default" name="upload" type="button">
>             <span class="glyphicon glyphicon-upload"></span>
>             <span>Upload</span>
>         </button>
>     </template>

How do i split this button to have a separate `Browse` and `Upload` button?

**Comment by talha-asad** [comment]
You could push the file object you receive from select function to an array and call the uploader when the upload button is clicked.
