### ISSUE TITLE
Name Email BrowseFile Submit

### ISSUE THREAD

**Issue by muscaiu** [jalik/jalik-ufs#67]
How would i have something like this working?
```
                <form action="action">
                    <input type="text" id="myName" name="myName">
                    <input type="text" id="myEmail" name="myEmail">
                    <input type="file" id="uploadFile">
                    <button type="submit" name="uploadFile">Upload file</button>
                </form>
```
I am able to add the name and email fields with autoform, and the files with ufs.
But i can not figure out how to attach the file to the user id.
Should it be 1 collection that holds the name, email, file or 2 separate collections and link them together by the id? Please help!

**Comment by jalik** [comment]
In your situation, the only way I see is to upload the file, then when you have the fileId you attach it to the user object you want to save :
```
{
myName : "something",
myEmail : "something@somewhere.com",
fileId : "id_of_the_file"
}
```

You must have 2 collections since one is needed to store file info (name, format, size, url...) and one for you users, after that it's up to you how you save the relationship, you can store the fileId in the user collection or the userId in the file collection, I can't choose for you.

You only show the HTML part of your code, don't you have the JS ?

**Comment by muscaiu** [comment]
U asked for it xD ... , oh and i lied about having the simple inputs xD 


**upload Button**
```
<template name="uploadForm">
        <button class="btn btn-default" name="upload" type="button">
            <span class="glyphicon glyphicon-upload"></span>
            <span>Upload</span>
        </button>
</template>
```
**Form template**
```
    <template name="NewCvForm">
            {{#autoForm id="insertCvForm" type="insert" collection="Cvs"}}
                {{> afQuickField name="name"}}
                {{> afQuickField name="email"}}
                {{> uploadForm}}
            {{/autoForm}}

            {{> fileTable}}
        </div>
    </template>
```
**CvCollections**
```
Cvs = new Mongo.Collection('cvs');
CvSchema = new SimpleSchema({
    name:{
        type: String,
    },
    email:{
        type: String,
    }
});
Cvs.attachSchema(CvSchema);
```

**Comment by muscaiu** [comment]
I understand. I do have the js, but i'm not sure what part i should post. 
If u are interested to take a look at [my repo](https://github.com/muscaiu/hr) while i take 3 days figuring it out please do. 
The project is adapted from LevelUpTuts RecipeBook project.

**Comment by fliip92** [comment]
you can resolve this?

**Comment by jalik** [comment]
I am sorry, I don't have the time and it does not concern UploadFS directly so I close this issue.
This kind of question should be posted on StackOverflow.
