### ISSUE TITLE
problems with aldeed:Collections2 or is it because I have done something wrong?

### ISSUE THREAD

**Issue by ruerob** [jalik/jalik-ufs#71]
Hello! :0)

When I try to upload a file, meteor gives me an error message. It occurs after I close the file select form. Have I done something wrong, or is it because I also use the aldeed:Collections2 package?

Exception while invoking method 'ufsDelete' Error: Match error: Expected string, got null
I20160825-12:51:35.584(2)?     at exports.check (packages/check/match.js:34:1)
I20160825-12:51:35.585(2)?     at [object Object].ufsDelete (packages/jalik:ufs/ufs-methods.js:117:9)
I20160825-12:51:35.588(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160825-12:51:35.589(2)?     at packages/ddp-server/livedata_server.js:711:19
I20160825-12:51:35.590(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160825-12:51:35.591(2)?     at packages/ddp-server/livedata_server.js:709:40
I20160825-12:51:35.592(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160825-12:51:35.594(2)?     at packages/ddp-server/livedata_server.js:707:46
I20160825-12:51:35.596(2)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160825-12:51:35.597(2)?     at packages/ddp-server/livedata_server.js:551:43

And here is what chrome says to me:

2_of_clubs.png upload has been aborted
NewReport.js:62 2_of_clubs.png has been created with ID FvwBmTpamrmJJsjeC
NewReport.js:68 2_of_clubs.png started
ufs-uploader.js:152 ufs: cannot remove file FvwBmTpamrmJJsjeC (Match failed [400])(anonymous function) @ ufs-uploader.js:152(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
NewReport.js:53 errorClass {error: 400, reason: "Match failed", details: undefined, message: "Match failed [400]", errorType: "Meteor.Error"}onError @ NewReport.js:53(anonymous function) @ ufs-uploader.js:153(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
NewReport.js:65 2_of_clubs.png 34.72657905892327% uploaded
NewReport.js:65 2_of_clubs.png 100% uploaded
NewReport.js:59 2_of_clubs.png has been uploaded

I've had a collection and a Store on both, client and server. And a template and helpers on the client side...
The Store is an UploadFS.store.Local

**Comment by jalik** [comment]
Hi, please provide the code you're using.

**Comment by ruerob** [comment]
Hello,
thank you for your answer. :0)

Here is the code:

I've loaded those 2 packages:
jalik:ufs
jalik:ufs-local

added this photostore in a file called fsstores/photostore.js:
```
Photos = new Mongo.Collection('photos');
    
PhotosStore = new UploadFS.store.Local({
    collection: Photos,
    name: 'photos',
    path: '/uploads/photos',
    mode: '0744', // directory permissions
    writeMode: '0744' // file permissions
});
```

here is the template I use:
```
<template name="NewReport">
    <div class="new-report-container">
        {{#autoForm collection="Reports" id="insertReportForm" type="insert" class="new-report-form"}}
            {{> afQuickField name='reporttype'}} <span id="reporttypes-button" class="wrench"><span class="fa fa-wrench"></span></span>
            <button type="button" name="upload">Select files</button>
            <button type="submit" class="btn btn-primary">Save</button>
        {{/autoForm}}
        
        {{> quickForm collection="Reports" id="insertReportForm" type="insert" class="new-report-form"}}
        
        {{#autoForm collection="ReportTypes" id="insertReportTypeForm" type="insert" class="new-reporttype-form"}}
            <div id="edit-reporttypes">
                {{> afQuickField name='name'}}
                <button type="submit" class="btn btn-primary">Hinzufügen</button>
            </div>
        {{/autoForm}}
    </div>
</template>
```

and here is the event:

```
Template.NewReport.events({
    'click #reporttypes-button'(event) {
        event.preventDefault();
        
        var div = document.getElementById('edit-reporttypes');
        if(div.style.display==="none"){
            div.style.display = "block";
        }else{
            div.style.display = "none";
        }
    },
    
    'click button[name=upload]': function (ev) {
        var self = this;

        UploadFS.selectFiles(function (file) {
            // Prepare the file to insert in database, note that we don't provide an URL,
            // it will be set automatically by the uploader when file transfer is complete.
            var photo = {
                name: file.name,
                size: file.size,
                type: file.type,
                customField1: 1337,
                customField2: {
                    a: 1,
                    b: 2
                }
            };

            // Create a new Uploader for this file
            var uploader = new UploadFS.Uploader({
                // This is where the uploader will save the file
                store: PhotosStore,
                // Optimize speed transfer by increasing/decreasing chunk size automatically
                adaptive: true,
                // Define the upload capacity (if upload speed is 1MB/s, then it will try to maintain upload at 80%, so 800KB/s)
                // (used only if adaptive = true)
                capacity: 0.8, // 80%
                // The size of each chunk sent to the server
                chunkSize: 8 * 1024, // 8k
                // The max chunk size (used only if adaptive = true)
                maxChunkSize: 128 * 1024, // 128k
                // This tells how many tries to do if an error occurs during upload
                maxTries: 5,
                // The File/Blob object containing the data
                data: file,
                // The document to save in the collection
                file: photo,
                // The error callback
                onError: function (err) {
                    console.error(err);
                },
                onAbort: function (file) {
                    console.log(file.name + ' upload has been aborted');
                },
                onComplete: function (file) {
                    console.log(file.name + ' has been uploaded');
                },
                onCreate: function (file) {
                    console.log(file.name + ' has been created with ID ' + file._id);
                },
                onProgress: function (file, progress) {
                    console.log(file.name + ' ' + (progress*100) + '% uploaded');
                },
                onStart: function (file) {
                    console.log(file.name + ' started');
                },
                onStop: function (file) {
                    console.log(file.name + ' stopped');
                },
            });

            // Starts the upload
            uploader.start();

            // Stops the upload
            uploader.stop();

            // Abort the upload
            uploader.abort();
        });
    }
});
```

I hope this helps you to help me. :0)
And again thank you for taking time to help me.

**Comment by vnmone** [comment]
You call 3 methods nearly in same time.

**Comment by ruerob** [comment]
oh... at the end of UploadFS.selectFiles, right?

**Comment by vnmone** [comment]
@ruerob yes, try to remove uploader.stop() and uploader.abort()

**Comment by ruerob** [comment]
Sometimes I sit on my eyes... 
Now everything works fine! :0)
Thank you very very much!!!
