### ISSUE TITLE
How to get file info after upload

### ISSUE THREAD

**Issue by fliip92** [jalik/jalik-ufs#72]
how i can get the url or id of file which i upload without subscription at the collection 
when i try get some data of file (into function : UploadFS.selectFiles(function (file) {}) i lost de context and i lost the data

**Comment by jalik** [comment]
Use the `onComplete` callback of the `UploadFS.Uploader`.

```js
uploader = new UploadFS.Uploader({/* .. options ..*/});
uploader.onComplete(function(file) {
  // do what you want with the file object
  console.log(file);
});
