### ISSUE TITLE
HTTP Upload via POST

### ISSUE THREAD

**Issue by noris666** [jalik/jalik-ufs#74]
Hello ! 
I need upload files via REST route, how i can do this ? I read package can process POST requests, but i dont find example here.

**Comment by jalik** [comment]
Hi @noris666, currently you cannot define the full path for file uploads/downloads.
The only thing you can change is the root path of the stores.
```js
// This path will be appended to the site URL, be sure to not put a "/" as first character
// for example, a PNG file with the _id 12345 in the "photos" store will be available via this URL :
// http://www.yourdomain.com/uploads/photos/12345.png
UploadFS.config.storesPath = 'uploads';
```

**Comment by noris666** [comment]
@jalik ok thx 4 answer. 
At the moment I realized uploading via POST request. Through these packages Picker, Multer and Meteor Files.

**Comment by noris666** [comment]
@jalik you can close my issue. I have solution at now.
If anybody need solutions. Can get here: https://github.com/noris666/Meteor-Files-POST-Example
