### ISSUE TITLE
Thumbs subscription keeps unsubscribing in prod environment

### ISSUE THREAD

**Issue by CaseyDStein** [jalik/jalik-ufs#75]
So I created a Meteor app that has an image upload feature based heavily on the image upload functionality in the Socially tutorial.  That tutorial has me doing the following on the server:

```js
import { UploadFS } from 'meteor/jalik:ufs';
import { Images, Thumbs } from './collection';

export const ThumbsStore = new UploadFS.store.GridFS({
    collection: Thumbs,
    name: 'thumbs',
    transformWrite(from, to, fileId, file) {
        // Resize to 100x100
        const gm = require('gm');
        const WIDTH = 100;
        const HEIGHT = 100;

        gm(from, file.name)
            .resize(WIDTH, HEIGHT)
            .gravity('Center')
            .extent(WIDTH, HEIGHT)
            .quality(75)
            .stream()
            .pipe(to);
    }
});

export const ImagesStore = new UploadFS.store.GridFS({
    collection: Images,
    name: 'images',
    filter: new UploadFS.Filter({
        contentTypes: ['image/*']
    }),
    copyTo: [
        ThumbsStore
    ]
});
```

and then subscribing to these collections on the client:

```js
        this.subscribe('thumbs', () => [
            this.getReactively('files', true) || []
        ]);

        this.subscribe('images');

        this.helpers({
            thumbs() {
                return Thumbs.find({
                    originalStore: 'images',
                    originalId: {
                        $in: this.getReactively('files', true) || []
                    }
                });
            },

            image() {
                return Images.findOne({
                    _id: this.getReactively('selectedImageId')
                });
            }
        });
```

When I run it locally on localhost:3000 it runs great, images get uploaded, and the thumbs collection gets populated correctly.

However, when I deploy my app to the production environment, the "thumbs" subscription keeps getting unsubscribed and uploaded files never get copied into it. So my "images" collection has all the images, but the "thumbs" collection is completely empty. Using the Meteor dev tools for Chrome I can see the following messages sent over DDP:
```
subscribing to thumbs with PEAbhgKe7eukJoj7y "{"msg":"sub","id":"zYjmkFEHB68QpvZQQ ... } 
unsubscribing from thumbs "{"msg":"unsub","id":"PiZzG2W8uafKbsKta"}" 
subscription ready for thumbs "{"msg":"ready","subs":["zYjmkFEHB68Q ... } 
unsubscribed from thumbs "{"msg":"nosub","id":"PiZzG2W8uafKbsKta"}"
```
I would appreciate any help you all could provide.

Casey

**Comment by jalik** [comment]
Hi @CaseyDStein, you should investigate the behavior of your `this.getReactively()` method which is the one that make the subscription change. Otherwise this issue is out of the scope of UploadFS. Please post it on StackOverflow or Meteor forums.
