### ISSUE TITLE
UploadFS.store constructor

### ISSUE THREAD

**Issue by vnmone** [jalik/jalik-ufs#76]
Is it nesessary to run constructor both on client and server?
Id like to use process.env.variable to set local store path, but now i cant.

**Comment by jalik** [comment]
Some methods on the client are using the store instance as parameter so yes it's required that the store is available on both environments.
Why cannot you use the process.env.variable ?

**Comment by vnmone** [comment]
its undefined on client

**Comment by vnmone** [comment]
solved, but looks not graceful:
```
Files = new Mongo.Collection('files');

if (Meteor.isServer) {
    Meteor.methods({
        'getPath': function () {
            return process.env.PATH_TO_CONTENT
        }
    });
}

FilesStore = {};

Meteor.call('getPath', function(e,r){
    if (r) {
        let path = r;
        FilesStore = new UploadFS.store.Local({
            collection: Files,
            name: 'files',
            path: path
        });
    }
});
```

**Comment by jalik** [comment]
@vnmone Okay now I understand what was your problem sorry... so I think you can simplify your code :
```js
Files = new Mongo.Collection('files');
let path = null;

if (Meteor.isServer) {
    path = process.env.PATH_TO_CONTENT;
}
FilesStore = new UploadFS.store.Local({
    collection: Files,
    name: 'files',
    path: path
});
```

**Comment by vnmone** [comment]
No, this code doesnt work.
Path will be set on server, but stay null on client.

**Comment by jalik** [comment]
Oh yea... ok I'll try to see if I can fix that in the next release ASAP. Thanks for the issue.

**Comment by vnmone** [comment]
It will be great!
