### ISSUE TITLE
Exception while invoking method 'ufsComplete' MongoError: File does not exist

### ISSUE THREAD

**Issue by JulianKingman** [jalik/jalik-ufs#79]
For some reason I'm able to upload files just fine locally, but on my live deployed environment I get the following error:
`Exception while invoking method 'ufsComplete' MongoError: File does not exist`
Any idea why I'm getting this error?

**Comment by jalik** [comment]
@JulianKingman, sorry for the late response, you must have a bad configuration.
- What store are you using ? (LocalStore, GridFS...)
- Does your temporary upload folder have the right permissions ?
- Does the server print something to the console ?
- Does the client print someting to the console ?
- Are the files uploaded to the temp folder ? (try to upload a large file and check the content of the temp folder to see if the file is created)

Debugging on a distant server is always complicated, but not impossible.
Give more details please.

**Comment by JulianKingman** [comment]
Ah, good question. I'm using GridFS, but I decided to substitute cloudinary for storage without thinking about the fact that I'm still using GridFS for the store. I suppose to use cloudinary I'd need to create a separate package for handling it as a store?

**Comment by jalik** [comment]
I was about to start a store for Cloudinary support in UFS some months before now but I had no time to work on it... If you intend to create yourself I would kindly help you if you need.

But that's another subject, for this issue, did you solve it ?
