### ISSUE TITLE
FYI: Exception while invoking method 'ufsComplete' Error: Did not check() all arguments

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#82]
Hi @jalik,

Just updated my app to v0.6.8. Everything looks fine, except that when uploading new files, I receive the following message:
`Exception while invoking method 'ufsComplete' Error: Did not check() all arguments during call to 'ufsComplete'`

Sure it's not critical but could you please add this check?

Have a great weekend!

**Comment by jalik** [comment]
I don't call `check()` but I actually check arguments with finer tests that returns more precise errors than `check` does, so I don't see the interest to use `check` instead sorry. You should find a way to disable the package you've installed to audit methods.
