### ISSUE TITLE
Exception while invoking method 'ufsImportURL' TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gbardwell** [jalik/jalik-ufs#84]
`With` the latest:
jalik:ufs@0.6.8
jalik:ufs-local@0.2.6

I am able to upload an image into a local store just fine...from desktop.

When I try:
let attr = { name: 'from web', description: 'no idea' };
            UploadFS.importFromURL(feedItem.image, attr, UploadImagesStore, (err, file)=> {
                if (err) {
                    console.error(err);
                    this.errMsg.set('Error: ' + err.message);
                } else {
                    console.log('Photo saved :', file);
                    this.selectedItem.share.image_url = file.url;
                    this.selectedItem.share.image_id = file._id;
                    this.tempImage.set(file.url);
                }
            });

I get:

I20160920-09:18:31.338(-4)? Exception while invoking method 'ufsImportURL' TypeError: Cannot read property 'replace' of undefined
I20160920-09:18:31.340(-4)?     at packages/jalik:ufs/ufs-filter.js:127:35
I20160920-09:18:31.340(-4)?     at checkContentType (packages/jalik:ufs/ufs-filter.js:121:12)
I20160920-09:18:31.341(-4)?     at [object Object].self.check (packages/jalik:ufs/ufs-filter.js:61:40)
I20160920-09:18:31.342(-4)?     at [object Object].ufsImportURL (packages/jalik:ufs/ufs-methods.js:165:31)
I20160920-09:18:31.342(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160920-09:18:31.342(-4)?     at packages/ddp-server/livedata_server.js:711:19
I20160920-09:18:31.342(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160920-09:18:31.342(-4)?     at packages/ddp-server/livedata_server.js:709:40
I20160920-09:18:31.342(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160920-09:18:31.343(-4)?     at packages/ddp-server/livedata_server.js:707:46
I20160920-09:18:31.343(-4)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160920-09:18:31.343(-4)?     at packages/ddp-server/livedata_server.js:551:43

Error class returns:
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}

Store is defined:

export const UploadImages = new Mongo.Collection<Image>('uploadimages');

export const UploadImagesStore = new UploadFS.store.Local({
    collection: UploadImages,
    name: 'uploadimages',
    path: '/uploads/photos',
    mode: '0744', // directory permissions
    writeMode: '0744', // file permissions
    filter: new UploadFS.Filter({
        contentTypes: ['image/*']
    }),
});

Thanks,
Greg

**Comment by gbardwell** [comment]
Perhaps the documentation is incomplete, but I worked around this by adding the extensions in the attr and setup.

export const UploadImagesStore = new UploadFS.store.Local({
    collection: UploadImages,
    name: 'uploadimages',
    path: '/uploads/photos',
    mode: '0744', // directory permissions
    writeMode: '0744', // file permissions
    filter: new UploadFS.Filter({
        contentTypes: ['image/*'],
        extensions: ['jpg', 'jpeg', 'png', 'gif']
    }),
});

In my code:

    let attr = { name: 'from web', description: 'no idea', client_id: this.mainDD.clientSelected,  type: "image/png", extension : "png"};
            if (feedItem.image.endsWith(".jpg") ||feedItem.image.endsWith(".jpg") ){
                attr.type = "image/jpg";
                attr.extension = "jpg";
            }
            if (feedItem.image.endsWith(".gif") ||feedItem.image.endsWith(".GIF") ){
                attr.type = "image/gif";
                attr.extension = "gif";
            }
            if (feedItem.image.endsWith(".jpeg") ||feedItem.image.endsWith(".JPEG") ){
                attr.type = "image/jpeg";
                attr.extension = "jpeg";
            }

**Comment by jalik** [comment]
@gbardwell yes the doc is not very complete, I am sorry for that.
Hopefully you found yourself how to fix the issue.

Importing from an URL is a little more difficult than just uploading a file, since UploadFS have to collect automatically informations from the URL. Currently it simply get the file name, extract the extension and assign the MIME type like "image/${extension}", yes "image/" is hardcoded, damn I was sleepy when I wrote this because it could be other type than image... I'll fix that and I can add some auto detections of MIME type but it'll depend on the file extension so if it's missing in the URL, you must find a way to define it manually.

So if you have and pass file info to the import method everything will be fine, otherwise you rely on automatic detection based on the URL which is not 100% viable.

**Comment by jalik** [comment]
Version `v0.6.9` has been published.
https://github.com/jalik/jalik-ufs#importing-file-from-a-url-server
