### ISSUE TITLE
new method getFileRelativeURLByOriginalId

### ISSUE THREAD

**Issue by maxwarch** [jalik/jalik-ufs#85]
Hi,

it will be cool to add this method to search image by originalId

````
UploadFS.Store.prototype.getFileRelativeURLByOriginalId = function (fileId) {
    let file = this.getCollection().findOne({originalId: fileId}, {fields: {name: 1}});
    return file && this.getRelativeURL(file._id + '/' + encodeURIComponent(file.name));
};
````

Your library is very nice ! Thanks.

**Comment by jalik** [comment]
@maxwarch I am sorry to say that it's not possible since a file having the `originalId` attribute is a copy of a file, this means that the orginal file can have several copies, so returning the first copy of a file is useless if you have much more copies, am I clear ? it's like russian roulette.

**Comment by maxwarch** [comment]
Thanks, i understand.
