### ISSUE TITLE
What is the best place to change file format?

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#86]
Hi,

This is a question. 

Suppose that we need to convert some uploaded files, for example, from the MIME type `type1` and extension `ext1` to `type2` and `ext2`. The conversion itself is made with a 3rd-party package. But except the conversion of the file (binary) data we have to change the file information in the corresponding collection, as well as the field `contentType` in the store. So, what is the best place to do that?

At a first glance, we can do that in many places. One of them is the `transformWrite` method, for example:

``` javascript
  transformWrite: function (from, to, fileId, file) {
    if (file.type !== 'type1') {
      from.pipe(to);
      return;
    }

   [ PLACE 1 ]

    dataConversionFuction(from)
      .setSomeOptions()
      .on('error', function (err) {
        console.log('Error happened: ' + err.message);
        from.pipe(to);
      })
      .on('end', function () {
        console.log('Converted successfully');
        [ PLACE 2 ]
      })
      .pipe(to);
  },
```

Another candidate is `onFinishUpload`:

``` javascript
someStore.onFinishUpload = function (file) {
    Files.update({_id: file._id}, 
        {$set: 
            { PLACE 3: CHANGE "name", "type", "extension", "url" FIELDS HERE }
        }
    );
};
```

Although it looks a little far-fetched, but we could change `name` and `type` also when calling `UploadFS.Uploader` (changing its `file` property) and then convert the file data in `transformWrite`. And so on.

But what is the most proper place from the point of view of the UFS work flow?
That is my question.

**Comment by jalik** [comment]
`onFinishUpload` is what you want, do not push database related code into transform methods, they are called only when a `transformRead` or `transformWrite` is defined and are not intended to be used for other than that.
