### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by talha-asad** [jalik/jalik-ufs#90]
Particularly `matb33:collection-hooks`

**Comment by kartboy16** [comment]
I'm getting an issue as well...

`Exception from sub myCollection id AiWq82DYW4fBTnJPM ReferenceError: myCollection is not defined
I20160926-14:48:00.160(-7)?     at Subscription.<anonymous> (server/main.js:42:12)
I20160926-14:48:00.160(-7)?     at packages/matb33_collection-hooks/collection-hooks.js:281:1
I20160926-14:48:00.161(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160926-14:48:00.161(-7)?     at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:280:1)
I20160926-14:48:00.161(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160926-14:48:00.162(-7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160926-14:48:00.163(-7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160926-14:48:00.166(-7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160926-14:48:00.168(-7)?     at packages/ddp-server/livedata_server.js:551:43`

**Comment by jalik** [comment]
@kartboy16 your error has nothing related with this issue, your var `myCollection` is just not defined (server/main.js:42:12)  as said in the error message.

**Comment by talha-asad** [comment]
Thanks @jalik 👍
