### ISSUE TITLE
How to update contentType in db.uploadfs.files collection? 

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#91]
Hi, 

This is an addition to #86.

Package: `UFS 0.6.9_1` + `ufs-gridfs`. 
I convert a file from an initial format to another one in `transformWrite` and then update `name`, `type`, `extension`, `path`, and `url` fields in the corresponding collection in the `onFinishUpload` method:
```javascript
MyCollection.update({_id: file._id}, {
  $set: {
    name: file.name.replace(/.oga/, '.' + newExt),
    type: newType,
    extension: newExt,
    path: file.path.replace(/.oga/, '.' + newExt),
    url: file.url.replace(/.oga/, '.' + newExt),
  },
});
``` 
But there is also such a field as `contentType` in `db.uploadfs.files` collection.

**Question**: Is it necessary to change this field? 
**If the answer is `YES`**: How to do it correctly from the `onFinishUpload` method -- without destroying something in the UFS work?

Thank you in advance for the answer.

**Comment by jalik** [comment]
Hi @seabrus, as I see the `contentType` attribute you are talking is added by GridFS, not UploadFS.
So I would says YES, you should change it to reflect the real type of the file, but I don't think you could break something in the UploadFS process by changing this value in the `onFinishUpload` method.

The file type is used to return headers when accessing the file on the server (HTTP: GET). I guess GridFS needs this info for the same purpose.

I am glad I can help you.

**Comment by seabrus** [comment]
@jalik I change `contentType` in `onFinishUpload` now.
Have a nice day!
