### ISSUE TITLE
Not seekable audio files in Chrome - "Range"/"Partial Content" support should be added? 

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#92]
Hi,

Working with audio files stored with the help of `UFS` and `ufs-gridfs`, I've found that in Chrome they are not seekable when playing them in the HTML5 audio player (tag `<audio ...>`). However, in Firefox there is no such a problem. 

:one: Googling the web, I found that it may be related to the ability of the server to correctly process  `Range` header in the browser request - see [here](http://stackoverflow.com/questions/2798931/seeking-through-a-streamed-mp3-file-with-html5-audio-tag):

> Make sure the server accepts `Range` requests, you can check to see if `Accept-Ranges` is in the header

and especially [here - see subsection "Byte-Range Requests"](http://www.jplayer.org/latest/developer-guide/#jPlayer-server-response):

>  Your server must enable Range requests. This is easy to check for by seeing if your server's response includes the Accept-Ranges in its header. Most HTML5 browsers enable seeking to new file positions during a download, so the server must allow the new Range to be requested.
Failure to accept byte Range requests will cause problems on some HTML5 browsers... 
**Chrome** tends to be the browser that has most problems if the Range request is not enabled on the server, but all browsers will have some issue even if it is only that you have to wait for all the media to load before jumping close to the end.   

#### :two: Valuable recommendations 
are also given in [Can't seek html5 video or audio in chrome](http://stackoverflow.com/questions/10583931/cant-seek-html5-video-or-audio-in-chrome) and [HTML5 video will not loop (GridFS)](http://stackoverflow.com/questions/8088364/html5-video-will-not-loop):
> Our server doesn't understand _partial content_ right now. As a result chrome is sending requests for content that doesn't get answered which in turn makes our video's and audio unseekable (and unloopable).

 and

> As it turns out, looping (or any sort of seeking, for that matter) in <video> elements on Chrome only works if the video file was served up by a server that understands _partial content_ requests. i.e. the server needs to honor requests that contain a "Range" header with a 206 "Partial Content" response. This is even the case if the video is small enough to be fully buffered by chrome, and no more server-round trips are made: if your server didn't honor chrome's Range request the first time, the video will not be loopable or seekable.

**_(see more details at the links above)_**

#### :three:  Checking my Chrome console 
I found that it contains `Range` request too:

![header2](https://cloud.githubusercontent.com/assets/10603559/18890356/67bd77d8-8509-11e6-9410-70949a39a69d.jpg)

#### :white_check_mark: Suggestion
I'm not sure but if `UFS` influences the server headers and server response when uploading a file from the GridFS, it could be nice to take into account the abovementioned recommendations and process the `Range` requests from Chrome (and possibly from other browsers).

Sorry if this suggestion has no relation to your package.

### P.S. 
I also understood that just the reason discussed above may be responsible for sudden stopping playing HTML5 `<audio>` in Chrome (in some cases with the error message `Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`).

**Comment by jalik** [comment]
Hi @seabrus, I need more time to dig into that issue, but I think that adding the header won't be enough, I would maybe have to handle this case and return the byte range on server side.
Please be patient. Thanks.

**Comment by seabrus** [comment]
Hi @jalik, thanks for your efforts and support!

**Comment by jalik** [comment]
@seabrus the `0.7.0_2` should fix your problem.

**Comment by seabrus** [comment]
@jalik thank a lot! It is a pleasure to work with you
