### ISSUE TITLE
Any way to load such image?

### ISSUE THREAD

**Issue by dufia** [jalik/jalik-ufs#93]
I am trying to switch from collection-fs, I have one big problem, I am unable to do this anymore:

_Images.insert('http://www1.cdn.sherdog.com/image_crop/200/300/_images/fighter/1393264951827Q0013.jpg', function (err, fileObj) {
})_    

Of cause I tried _Meteor.imagesStore.importFromURL_, it will not work

I guess its because server-side, image link morphs into:
_http://www.sherdog.com/image_crop.php?image=http://www.origin.sherdog.com/_images/fighter/1393264951827Q0013.jpg&&width=200&&height=300_

I am aware of this:

`WARNING: File type detection is based on the file name in the URL so if the URL is obfuscated it won't work (http://www.hello.com/images/123456 won't work, http://www.hello.com/images/123456.png will work).`

But... What do you suggest?

Should I look for another upload library? Could it be done with UplodFS?

**Comment by jalik** [comment]
1. I don't get why you are passing a string in Images.insert(), it should be an object.
2. If you're trying to import a distant file (from another location), the native solution is to use `UploadFS.importFromURL()`
3. If you want to support "constructed URLs" you need a parser, that can reorganize query string to make it ready for UploadFS : the result would be http://www.sherdog.com/image_crop.php?&width=200&height=300&image=http://www.origin.sherdog.com/_images/fighter/1393264951827Q0013.jpg (the URL ends with the file name + file extension)
4. You could force users to set the file name or do that yourself

**Comment by dufia** [comment]
Images.insert() is the code I used with collection-fs

Thanks for help, Ill try your advice. Please don't close this issue yet.

**Comment by jalik** [comment]
@dufia Did you found a solution ? this  may help future people in your case, also it could help me improving the lib if you did some work on your side.

**Comment by dufia** [comment]
@jalik Well, I parsed out url like that from the original url: `http://www.origin.sherdog.com/_images/fighter/1393264951827Q0013.jpg`

I don't know why but I couldn't rely on file extension filter. Sometimes it would filter out files with clear jpg extension. I worked around it but there might be something wrong there.
