### ISSUE TITLE
"Range"/"Partial Content" support for Chrome: Part 2

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#94]
Hi,

See the prehistory at #92. 

Today I've tested the version `0.7.0_2`. 
**Browser:** Chromium (version `52.0.2743.116 Built on Ubuntu`). 
**Update (2016 Oct 10)**: 
 -- The same results as described below are found for Chrome `53.0.2785.143 (64-bit)`
 -- But none of issues described below encounter on Firefox: on FF all files play and seek correctly. 

Here are the results.

:one: I can correctly seek audio files that are played with the help of the `<audio ...>` tag and with size at least not more than 3.1 MB. 

:red_circle: But if I use `<audio preload="auto" ...>` I encounter cases when the file starts playing, then suddenly resets and restarts from the 32768-th byte. In such cases the browser request contains `Range=32768-`, and the server indicates in its response that it sends range from 32768 to the end of the file. But in fact the player plays the file from the start (from the 0-th byte), and then stops playing not exactly at the end of the audio file but at the end minus 32768 bytes, in other words, it cut the file. 

:two: There are problems with seeking if the file size is about 16MB. If I move the slider, the player always plays from the start of the file, not from the position indicated by the slider. Checking the console, I see that after every change of the slider position the browser sends a new request with `Range=[NewPosition]-` (e.g., `Range=123547-`). The server answers with headers that indicate that `[NewPosition]-[EndOfFile]` bytes are sent. But actually it looks like the player gets `0-[EndOfFile-NewPosition]` bytes. 

Moreover, the listing of such a file loading (size = `15,964,411` bytes, playing time = `33m : 11s`, no seeking, no transformation of the initial file) looks like that:
* Initial request-response:
![0](https://cloud.githubusercontent.com/assets/10603559/19129948/f6509eaa-8b51-11e6-8ff7-f5f7e42e9675.png)

* First portion:
![1](https://cloud.githubusercontent.com/assets/10603559/19130078/6ec71d1e-8b52-11e6-96d7-b5ffe3cf66d6.png)

* Next portions:
![2](https://cloud.githubusercontent.com/assets/10603559/19130181/d51644a0-8b52-11e6-93a5-fc3270a63524.png)
![3](https://cloud.githubusercontent.com/assets/10603559/19130182/d5213b1c-8b52-11e6-9f88-0494490b8924.png)
![4](https://cloud.githubusercontent.com/assets/10603559/19130185/d524c87c-8b52-11e6-92e6-989b3bd88800.png)
![5](https://cloud.githubusercontent.com/assets/10603559/19130183/d5224fc0-8b52-11e6-9430-b2cc3250210a.png)
![6](https://cloud.githubusercontent.com/assets/10603559/19130186/d52551e8-8b52-11e6-9c93-046c337e58a1.png)
![7](https://cloud.githubusercontent.com/assets/10603559/19130184/d5242b2e-8b52-11e6-9b68-e5214fd1487c.png)
![8](https://cloud.githubusercontent.com/assets/10603559/19130187/d532d656-8b52-11e6-867c-90784579e479.png)
![9](https://cloud.githubusercontent.com/assets/10603559/19130188/d53a75a0-8b52-11e6-9e02-07d9d47269b1.png)
![10](https://cloud.githubusercontent.com/assets/10603559/19130591/721fe368-8b54-11e6-8d9c-16e99a71aead.png)

* It fails with the error:
![11](https://cloud.githubusercontent.com/assets/10603559/19130215/f5882eec-8b52-11e6-87ae-08788766b723.png)

* After that the player doesn't stop playing, it sends a new request:
![00](https://cloud.githubusercontent.com/assets/10603559/19130255/23511b18-8b53-11e6-9554-038d1169af31.png)

*... and new portions of bytes are (giving in sum the total file size):
![12](https://cloud.githubusercontent.com/assets/10603559/19130280/382ec1de-8b53-11e6-9f76-1084f624253e.png)
![12a](https://cloud.githubusercontent.com/assets/10603559/19130281/3830c948-8b53-11e6-8c47-10c7b2d02f16.png)

* Then it reaches the end time (33:11) and stops.

### Some thoughts
:white_check_mark: Two ideas come to my mind after that testing.
* There could be something quite easy that leads to sending bytes from 0, not from a required position
* There could be some other reason for the fail `net::ERR_CONTENT_LENGTH_MISMATCH`

If some other info could be useful and necessary, I'll be glad to provide it.

**Comment by jalik** [comment]
@seabrus All my apologies, I forgot to really "cut" the stream and return the needed part... it involed some changes on store plugins, however I can only maintain the LocalStore and the GridFSStore, other stores are not from me and they must implement the stream range option.

**Comment by seabrus** [comment]
@jalik sorry, I didn't mentioned that I used GridFS. So yes, GridFSStore is the most important for me.
Thanks for changes, I'll test them today!
