### ISSUE TITLE
Got permission error

### ISSUE THREAD

**Issue by zh-wowtv** [jalik/jalik-ufs#96]
I got the following error message:

> W20161014-16:23:24.599(8)? (STDERR) ufs: permissions are not defined for store "thumbs"
> W20161014-16:23:24.605(8)? (STDERR) ufs: permissions are not defined for store "images"

But it seems it won't affect file uploading. Any idea? Thanks.

**Comment by jereckley** [comment]
Same here... happened after I tried to restore a previous version of the meteor mongo db from an older version of meteor. 

It didn't work and my attempt to recover from that has failed.. meteor reset, meteor rebuild, reinstalling meteor has failed. Now I just get this error:

<img width="678" alt="screenshot 2016-10-15 00 49 13" src="https://cloud.githubusercontent.com/assets/3599183/19407487/61748be4-9271-11e6-96fe-f8add935f6cc.png">

In the console it shows as this:

<img width="893" alt="screenshot 2016-10-15 00 51 16" src="https://cloud.githubusercontent.com/assets/3599183/19407492/817469f0-9271-11e6-8124-37c245943ec1.png">

The thing is there is no profile with the profile id shown so its like a version of that db is still being queried but doesn't exist - when I go into mongo the collections have been removed like you would expect meteor reset to do.

**Comment by jalik** [comment]
@zh-wowtv It's not an error, but a warning that tells you that you don't have define permissions for the mentioned store, so the default permissions are used.
You must define your application permissions to allow or deny depending on your rules, UFS cannot do that for you so by default it allows everything.

**Comment by jalik** [comment]
@jereckley in your console, you have 2 warnings from UFS, read the previous comment to understand why. The error is thrown because of something wrong in your code or database (since you said you restored the db), it's not related to UploadFS.
