### ISSUE TITLE
The s3 plugin is broken

### ISSUE THREAD

**Issue by dufia** [jalik/jalik-ufs#99]
Sorry to point this out, just check https://github.com/sebakerckhof/ufs-s3/issues/4

**Comment by jalik** [comment]
@dufia I am sorry I don't provide support for external projects, my own are already time consuming.

As @sebakerckhof said you should checkout the ufs-s3 repository, put it in your Meteor app "packages" folder and test if the problem is still alive. Hope you'll find a way to fix your error.
